//
//  File.swift
//  Swift_UIKit_ChatApp
//
//  Created by Al-Tameemi Hayder on 26.10.2023.
//

let flagsEmojis: [EmojiObject] = [
    EmojiObject(keyWord: "White Flag", emoji: "🏳️"),
    EmojiObject(keyWord: "Black Flag", emoji: "🏴"),
    EmojiObject(keyWord: "Chequered Flag", emoji: "🏁"),
    EmojiObject(keyWord: "Triangular Flag", emoji: "🚩"),
    EmojiObject(keyWord: "Rainbow Flag", emoji: "🏳️‍🌈"),
    EmojiObject(keyWord: "Afghanistan", emoji: "🇦🇫"),
    EmojiObject(keyWord: "Åland Islands", emoji: "🇦🇽"),
    EmojiObject(keyWord: "Albania", emoji: "🇦🇱"),
    EmojiObject(keyWord: "Algeria", emoji: "🇩🇿"),
    EmojiObject(keyWord: "American Samoa", emoji: "🇦🇸"),
    EmojiObject(keyWord: "Andorra", emoji: "🇦🇩"),
    EmojiObject(keyWord: "Angola", emoji: "🇦🇴"),
    EmojiObject(keyWord: "Anguilla", emoji: "🇦🇮"),
    EmojiObject(keyWord: "Antarctica", emoji: "🇦🇶"),
    EmojiObject(keyWord: "Antigua & Barbuda", emoji: "🇦🇬"),
    EmojiObject(keyWord: "Argentina", emoji: "🇦🇷"),
    EmojiObject(keyWord: "Armenia", emoji: "🇦🇲"),
    EmojiObject(keyWord: "Aruba", emoji: "🇦🇼"),
    EmojiObject(keyWord: "Australia", emoji: "🇦🇺"),
    EmojiObject(keyWord: "Austria", emoji: "🇦🇹"),
    EmojiObject(keyWord: "Azerbaijan", emoji: "🇦🇿"),
    EmojiObject(keyWord: "Bahamas", emoji: "🇧🇸"),
    EmojiObject(keyWord: "Bahrain", emoji: "🇧🇭"),
    EmojiObject(keyWord: "Bangladesh", emoji: "🇧🇩"),
    EmojiObject(keyWord: "Barbados", emoji: "🇧🇧"),
    EmojiObject(keyWord: "Belarus", emoji: "🇧🇾"),
    EmojiObject(keyWord: "Belgium", emoji: "🇧🇪"),
    EmojiObject(keyWord: "Belize", emoji: "🇧🇿"),
    EmojiObject(keyWord: "Benin", emoji: "🇧🇯"),
    EmojiObject(keyWord: "Bermuda", emoji: "🇧🇲"),
    EmojiObject(keyWord: "Bhutan", emoji: "🇧🇹"),
    EmojiObject(keyWord: "Bolivia", emoji: "🇧🇴"),
    EmojiObject(keyWord: "Bonaire, Sint Eustatius & Saba", emoji: "🇧🇶"),
    EmojiObject(keyWord: "Bosnia & Herzegovina", emoji: "🇧🇦"),
    EmojiObject(keyWord: "Botswana", emoji: "🇧🇼"),
    EmojiObject(keyWord: "Brazil", emoji: "🇧🇷"),
    EmojiObject(keyWord: "British Indian Ocean Territory", emoji: "🇮🇴"),
    EmojiObject(keyWord: "British Virgin Islands", emoji: "🇻🇬"),
    EmojiObject(keyWord: "Brunei", emoji: "🇧🇳"),
    EmojiObject(keyWord: "Bulgaria", emoji: "🇧🇬"),
    EmojiObject(keyWord: "Burkina Faso", emoji: "🇧🇫"),
    EmojiObject(keyWord: "Burundi", emoji: "🇧🇮"),
    EmojiObject(keyWord: "Cabo Verde", emoji: "🇨🇻"),
    EmojiObject(keyWord: "Cambodia", emoji: "🇰🇭"),
    EmojiObject(keyWord: "Cameroon", emoji: "🇨🇲"),
    EmojiObject(keyWord: "Canada", emoji: "🇨🇦"),
    EmojiObject(keyWord: "Canary Islands", emoji: "🇮🇨"),
    EmojiObject(keyWord: "Cayman Islands", emoji: "🇰🇾"),
    EmojiObject(keyWord: "Central African Republic", emoji: "🇨🇫"),
    EmojiObject(keyWord: "Chad", emoji: "🇹🇩"),
    EmojiObject(keyWord: "Chile", emoji: "🇨🇱"),
    EmojiObject(keyWord: "China", emoji: "🇨🇳"),
    EmojiObject(keyWord: "Christmas Island", emoji: "🇨🇽"),
    EmojiObject(keyWord: "Cocos (Keeling) Islands", emoji: "🇨🇨"),
    EmojiObject(keyWord: "Colombia", emoji: "🇨🇴"),
    EmojiObject(keyWord: "Comoros", emoji: "🇰🇲"),
    EmojiObject(keyWord: "Congo - Brazzaville", emoji: "🇨🇬"),
    EmojiObject(keyWord: "Congo - Kinshasa", emoji: "🇨🇩"),
    EmojiObject(keyWord: "Cook Islands", emoji: "🇨🇰"),
    EmojiObject(keyWord: "Costa Rica", emoji: "🇨🇷"),
    EmojiObject(keyWord: "Côte d’Ivoire", emoji: "🇨🇮"),
    EmojiObject(keyWord: "Croatia", emoji: "🇭🇷"),
    EmojiObject(keyWord: "Cuba", emoji: "🇨🇺"),
    EmojiObject(keyWord: "Curaçao", emoji: "🇨🇼"),
    EmojiObject(keyWord: "Cyprus", emoji: "🇨🇾"),
    EmojiObject(keyWord: "Czechia", emoji: "🇨🇿"),
    EmojiObject(keyWord: "Denmark", emoji: "🇩🇰"),
    EmojiObject(keyWord: "Djibouti", emoji: "🇩🇯"),
    EmojiObject(keyWord: "Dominica", emoji: "🇩🇲"),
    EmojiObject(keyWord: "Dominican Republic", emoji: "🇩🇴"),
    EmojiObject(keyWord: "Ecuador", emoji: "🇪🇨"),
    EmojiObject(keyWord: "Egypt", emoji: "🇪🇬"),
    EmojiObject(keyWord: "El Salvador", emoji: "🇸🇻"),
    EmojiObject(keyWord: "Equatorial Guinea", emoji: "🇬🇶"),
    EmojiObject(keyWord: "Eritrea", emoji: "🇪🇷"),
    EmojiObject(keyWord: "Estonia", emoji: "🇪🇪"),
    EmojiObject(keyWord: "Eswatini", emoji: "🇸🇿"),
    EmojiObject(keyWord: "European Union", emoji: "🇪🇺"),
    EmojiObject(keyWord: "Falkland Islands", emoji: "🇫🇰"),
    EmojiObject(keyWord: "Faroe Islands", emoji: "🇫🇴"),
    EmojiObject(keyWord: "Fiji", emoji: "🇫🇯"),
    EmojiObject(keyWord: "Finland", emoji: "🇫🇮"),
    EmojiObject(keyWord: "France", emoji: "🇫🇷"),
    EmojiObject(keyWord: "French Guiana", emoji: "🇬🇫"),
    EmojiObject(keyWord: "French Polynesia", emoji: "🇵🇫"),
    EmojiObject(keyWord: "French Southern Territories", emoji: "🇹🇫"),
    EmojiObject(keyWord: "Gabon", emoji: "🇬🇦"),
    EmojiObject(keyWord: "Gambia", emoji: "🇬🇲"),
    EmojiObject(keyWord: "Georgia", emoji: "🇬🇪"),
    EmojiObject(keyWord: "Germany", emoji: "🇩🇪"),
    EmojiObject(keyWord: "Ghana", emoji: "🇬🇭"),
    EmojiObject(keyWord: "Gibraltar", emoji: "🇬🇮"),
    EmojiObject(keyWord: "Greece", emoji: "🇬🇷"),
    EmojiObject(keyWord: "Greenland", emoji: "🇬🇱"),
    EmojiObject(keyWord: "Grenada", emoji: "🇬🇩"),
    EmojiObject(keyWord: "Guadeloupe", emoji: "🇬🇵"),
    EmojiObject(keyWord: "Guam", emoji: "🇬🇺"),
    EmojiObject(keyWord: "Guatemala", emoji: "🇬🇹"),
    EmojiObject(keyWord: "Guernsey", emoji: "🇬🇬"),
    EmojiObject(keyWord: "Guinea", emoji: "🇬🇳"),
    EmojiObject(keyWord: "Guinea-Bissau", emoji: "🇬🇼"),
    EmojiObject(keyWord: "Guyana", emoji: "🇬🇾"),
    EmojiObject(keyWord: "Haiti", emoji: "🇭🇹"),
    EmojiObject(keyWord: "Honduras", emoji: "🇭🇳"),
    EmojiObject(keyWord: "Hong Kong SAR China", emoji: "🇭🇰"),
    EmojiObject(keyWord: "Hungary", emoji: "🇭🇺"),
    EmojiObject(keyWord: "Iceland", emoji: "🇮🇸"),
    EmojiObject(keyWord: "India", emoji: "🇮🇳"),
    EmojiObject(keyWord: "Indonesia", emoji: "🇮🇩"),
    EmojiObject(keyWord: "Iran", emoji: "🇮🇷"),
    EmojiObject(keyWord: "Iraq", emoji: "🇮🇶"),
    EmojiObject(keyWord: "Ireland", emoji: "🇮🇪"),
    EmojiObject(keyWord: "Isle of Man", emoji: "🇮🇲"),
    EmojiObject(keyWord: "Italy", emoji: "🇮🇹"),
    EmojiObject(keyWord: "Jamaica", emoji: "🇯🇲"),
    EmojiObject(keyWord: "Japan", emoji: "🇯🇵"),
    EmojiObject(keyWord: "Japanese", emoji: "🎌"),
    EmojiObject(keyWord: "Jersey", emoji: "🇯🇪"),
    EmojiObject(keyWord: "Jordan", emoji: "🇯🇴"),
    EmojiObject(keyWord: "Kazakhstan", emoji: "🇰🇿"),
    EmojiObject(keyWord: "Kenya", emoji: "🇰🇪"),
    EmojiObject(keyWord: "Kiribati", emoji: "🇰🇮"),
    EmojiObject(keyWord: "Kosovo", emoji: "🇽🇰"),
    EmojiObject(keyWord: "Kuwait", emoji: "🇰🇼"),
    EmojiObject(keyWord: "Kyrgyzstan", emoji: "🇰🇬"),
    EmojiObject(keyWord: "Laos", emoji: "🇱🇦"),
    EmojiObject(keyWord: "Latvia", emoji: "🇱🇻"),
    EmojiObject(keyWord: "Lebanon", emoji: "🇱🇧"),
    EmojiObject(keyWord: "Lesotho", emoji: "🇱🇸"),
    EmojiObject(keyWord: "Liberia", emoji: "🇱🇷"),
    EmojiObject(keyWord: "Libya", emoji: "🇱🇾"),
    EmojiObject(keyWord: "Liechtenstein", emoji: "🇱🇮"),
    EmojiObject(keyWord: "Lithuania", emoji: "🇱🇹"),
    EmojiObject(keyWord: "Luxembourg", emoji: "🇱🇺"),
    EmojiObject(keyWord: "Macao SAR China", emoji: "🇲🇴"),
    EmojiObject(keyWord: "Macedonia", emoji: "🇲🇰"),
    EmojiObject(keyWord: "Madagascar", emoji: "🇲🇬"),
    EmojiObject(keyWord: "Malawi", emoji: "🇲🇼"),
    EmojiObject(keyWord: "Malaysia", emoji: "🇲🇾"),
    EmojiObject(keyWord: "Maldives", emoji: "🇲🇻"),
    EmojiObject(keyWord: "Mali", emoji: "🇲🇱"),
    EmojiObject(keyWord: "Malta", emoji: "🇲🇹"),
    EmojiObject(keyWord: "Marshall Islands", emoji: "🇲🇭"),
    EmojiObject(keyWord: "Martinique", emoji: "🇲🇶"),
    EmojiObject(keyWord: "Mauritania", emoji: "🇲🇷"),
    EmojiObject(keyWord: "Mauritius", emoji: "🇲🇺"),
    EmojiObject(keyWord: "Mayotte", emoji: "🇾🇹"),
    EmojiObject(keyWord: "Mexico", emoji: "🇲🇽"),
    EmojiObject(keyWord: "Micronesia", emoji: "🇫🇲"),
    EmojiObject(keyWord: "Moldova", emoji: "🇲🇩"),
    EmojiObject(keyWord: "Monaco", emoji: "🇲🇨"),
    EmojiObject(keyWord: "Mongolia", emoji: "🇲🇳"),
    EmojiObject(keyWord: "Montenegro", emoji: "🇲🇪"),
    EmojiObject(keyWord: "Montserrat", emoji: "🇲🇸"),
    EmojiObject(keyWord: "Morocco", emoji: "🇲🇦"),
    EmojiObject(keyWord: "Mozambique", emoji: "🇲🇿"),
    EmojiObject(keyWord: "Myanmar (Burma)", emoji: "🇲🇲"),
    EmojiObject(keyWord: "Namibia", emoji: "🇳🇦"),
    EmojiObject(keyWord: "Nauru", emoji: "🇳🇷"),
    EmojiObject(keyWord: "Nepal", emoji: "🇳🇵"),
    EmojiObject(keyWord: "Netherlands", emoji: "🇳🇱"),
    EmojiObject(keyWord: "New Caledonia", emoji: "🇳🇨"),
    EmojiObject(keyWord: "New Zealand", emoji: "🇳🇿"),
    EmojiObject(keyWord: "Nicaragua", emoji: "🇳🇮"),
    EmojiObject(keyWord: "Niger", emoji: "🇳🇪"),
    EmojiObject(keyWord: "Nigeria", emoji: "🇳🇬"),
    EmojiObject(keyWord: "Niue", emoji: "🇳🇺"),
    EmojiObject(keyWord: "Norfolk Island", emoji: "🇳🇫"),
    EmojiObject(keyWord: "Northern Mariana Islands", emoji: "🇲🇵"),
    EmojiObject(keyWord: "North Korea", emoji: "🇰🇵"),
    EmojiObject(keyWord: "Norway", emoji: "🇳🇴"),
    EmojiObject(keyWord: "Oman", emoji: "🇴🇲"),
    EmojiObject(keyWord: "Pakistan", emoji: "🇵🇰"),
    EmojiObject(keyWord: "Palau", emoji: "🇵🇼"),
    EmojiObject(keyWord: "Palestinian Territories", emoji: "🇵🇸"),
    EmojiObject(keyWord: "Panama", emoji: "🇵🇦"),
    EmojiObject(keyWord: "Papua New Guinea", emoji: "🇵🇬"),
    EmojiObject(keyWord: "Paraguay", emoji: "🇵🇾"),
    EmojiObject(keyWord: "Peru", emoji: "🇵🇪"),
    EmojiObject(keyWord: "Philippines", emoji: "🇵🇭"),
    EmojiObject(keyWord: "Pitcairn Islands", emoji: "🇵🇳"),
    EmojiObject(keyWord: "Poland", emoji: "🇵🇱"),
    EmojiObject(keyWord: "Portugal", emoji: "🇵🇹"),
    EmojiObject(keyWord: "Puerto Rico", emoji: "🇵🇷"),
    EmojiObject(keyWord: "Qatar", emoji: "🇶🇦"),
    EmojiObject(keyWord: "Réunion", emoji: "🇷🇪"),
    EmojiObject(keyWord: "Romania", emoji: "🇷🇴"),
    EmojiObject(keyWord: "Russia", emoji: "🇷🇺"),
    EmojiObject(keyWord: "Rwanda", emoji: "🇷🇼"),
    EmojiObject(keyWord: "Saint Barthélemy", emoji: "🇧🇱"),
    EmojiObject(keyWord: "Saint Helena", emoji: "🇸🇭"),
    EmojiObject(keyWord: "Saint Kitts & Nevis", emoji: "🇰🇳"),
    EmojiObject(keyWord: "Saint Lucia", emoji: "🇱🇨"),
    EmojiObject(keyWord: "Saint Martin", emoji: "🇵🇲"),
    EmojiObject(keyWord: "Saint Vincent & Grenadines", emoji: "🇻🇨"),
    EmojiObject(keyWord: "Samoa", emoji: "🇼🇸"),
    EmojiObject(keyWord: "San Marino", emoji: "🇸🇲"),
    EmojiObject(keyWord: "São Tomé & Príncipe", emoji: "🇸🇹"),
    EmojiObject(keyWord: "Saudi Arabia", emoji: "🇸🇦"),
    EmojiObject(keyWord: "Senegal", emoji: "🇸🇳"),
    EmojiObject(keyWord: "Serbia", emoji: "🇷🇸"),
    EmojiObject(keyWord: "Seychelles", emoji: "🇸🇨"),
    EmojiObject(keyWord: "Sierra Leone", emoji: "🇸🇱"),
    EmojiObject(keyWord: "Singapore", emoji: "🇸🇬"),
    EmojiObject(keyWord: "Sint Maarten", emoji: "🇸🇽"),
    EmojiObject(keyWord: "Slovakia", emoji: "🇸🇰"),
    EmojiObject(keyWord: "Slovenia", emoji: "🇸🇮"),
    EmojiObject(keyWord: "Solomon Islands", emoji: "🇸🇧"),
    EmojiObject(keyWord: "Somalia", emoji: "🇸🇴"),
    EmojiObject(keyWord: "South Africa", emoji: "🇿🇦"),
    EmojiObject(keyWord: "South Georgia & South Sandwich Islands", emoji: "🇬🇸"),
    EmojiObject(keyWord: "South Korea", emoji: "🇰🇷"),
    EmojiObject(keyWord: "South Sudan", emoji: "🇸🇸"),
    EmojiObject(keyWord: "Spain", emoji: "🇪🇸"),
    EmojiObject(keyWord: "Sri Lanka", emoji: "🇱🇰"),
    EmojiObject(keyWord: "Sudan", emoji: "🇸🇩"),
    EmojiObject(keyWord: "Suriname", emoji: "🇸🇷"),
    EmojiObject(keyWord: "Svalbard & Jan Mayen", emoji: "🇸🇿"),
    EmojiObject(keyWord: "Sweden", emoji: "🇸🇪"),
    EmojiObject(keyWord: "Switzerland", emoji: "🇨🇭"),
    EmojiObject(keyWord: "Syria", emoji: "🇸🇾"),
    EmojiObject(keyWord: "Taiwan", emoji: "🇹🇼"),
    EmojiObject(keyWord: "Tajikistan", emoji: "🇹🇯"),
    EmojiObject(keyWord: "Tanzania", emoji: "🇹🇿"),
    EmojiObject(keyWord: "Thailand", emoji: "🇹🇭"),
    EmojiObject(keyWord: "Timor-Leste", emoji: "🇹🇱"),
    EmojiObject(keyWord: "Togo", emoji: "🇹🇬"),
    EmojiObject(keyWord: "Tokelau", emoji: "🇹🇰"),
    EmojiObject(keyWord: "Tonga", emoji: "🇹🇴"),
    EmojiObject(keyWord: "Trinidad & Tobago", emoji: "🇹🇹"),
    EmojiObject(keyWord: "Tunisia", emoji: "🇹🇳"),
    EmojiObject(keyWord: "Turkey", emoji: "🇹🇷"),
    EmojiObject(keyWord: "Turkmenistan", emoji: "🇹🇲"),
    EmojiObject(keyWord: "Turks & Caicos Islands", emoji: "🇹🇨"),
    EmojiObject(keyWord: "Tuvalu", emoji: "🇹🇻"),
    EmojiObject(keyWord: "Uganda", emoji: "🇺🇬"),
    EmojiObject(keyWord: "Ukraine", emoji: "🇺🇦"),
    EmojiObject(keyWord: "United Arab Emirates", emoji: "🇦🇪"),
    EmojiObject(keyWord: "United Kingdom", emoji: "🇬🇧"),
    EmojiObject(keyWord: "United States", emoji: "🇺🇸"),
    EmojiObject(keyWord: "United States Virgin Islands", emoji: "🇻🇮"),
    EmojiObject(keyWord: "Uruguay", emoji: "🇺🇾"),
    EmojiObject(keyWord: "Uzbekistan", emoji: "🇺🇿"),
    EmojiObject(keyWord: "Vanuatu", emoji: "🇻🇺"),
    EmojiObject(keyWord: "Vatican City", emoji: "🇻🇦"),
    EmojiObject(keyWord: "Venezuela", emoji: "🇻🇪"),
    EmojiObject(keyWord: "Vietnam", emoji: "🇻🇳"),
    EmojiObject(keyWord: "Wallis & Futuna", emoji: "🇼🇫"),
    EmojiObject(keyWord: "Western Sahara", emoji: "🇪🇭"),
    EmojiObject(keyWord: "Yemen", emoji: "🇾🇪"),
    EmojiObject(keyWord: "Zambia", emoji: "🇿🇲"),
    EmojiObject(keyWord: "Zimbabwe", emoji: "🇿🇼"),
    EmojiObject(keyWord: "England", emoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿"),
    EmojiObject(keyWord: "Scotland", emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿"),
    EmojiObject(keyWord: "Wales", emoji: "🏴󠁧󠁢󠁷󠁬󠁳󠁿")
]
