//
//  foodAndDrinksEmojisArray.swift
//  Swift_UIKit_ChatApp
//
//  Created by Al-Tameemi Hayder on 26.10.2023.
//

let foodAndDrinkEmojis: [EmojiObject] = [
    EmojiObject(keyWord: "Green Apple", emoji: "🍏"),
    EmojiObject(keyWord: "Red Apple", emoji: "🍎"),
    EmojiObject(keyWord: "Pear", emoji: "🍐"),
    EmojiObject(keyWord: "Tangerine", emoji: "🍊"),
    EmojiObject(keyWord: "Orange", emoji: "🍋"),
    EmojiObject(keyWord: "Banana", emoji: "🍌"),
    EmojiObject(keyWord: "Watermelon", emoji: "🍉"),
    EmojiObject(keyWord: "Grapes", emoji: "🍇"),
    EmojiObject(keyWord: "Strawberry", emoji: "🍓"),
    EmojiObject(keyWord: "Melon", emoji: "🍈"),
    EmojiObject(keyWord: "Cherries", emoji: "🍒"),
    EmojiObject(keyWord: "Peach", emoji: "🍑"),
    EmojiObject(keyWord: "Pineapple", emoji: "🍍"),
    EmojiObject(keyWord: "Kiwi", emoji: "🥝"),
    EmojiObject(keyWord: "Avocado", emoji: "🥑"),
    EmojiObject(keyWord: "Tomato", emoji: "🍅"),
    EmojiObject(keyWord: "Eggplant", emoji: "🍆"),
    EmojiObject(keyWord: "Cucumber", emoji: "🥒"),
    EmojiObject(keyWord: "Carrot", emoji: "🥕"),
    EmojiObject(keyWord: "Corn", emoji: "🌽"),
    EmojiObject(keyWord: "Hot Pepper", emoji: "🌶"),
    EmojiObject(keyWord: "Potato", emoji: "🥔"),
    EmojiObject(keyWord: "Sweet Potato", emoji: "🍠"),
    EmojiObject(keyWord: "Chestnut", emoji: "🌰"),
    EmojiObject(keyWord: "Peanuts", emoji: "🥜"),
    EmojiObject(keyWord: "Honey Pot", emoji: "🍯"),
    EmojiObject(keyWord: "Croissant", emoji: "🥐"),
    EmojiObject(keyWord: "Bread", emoji: "🍞"),
    EmojiObject(keyWord: "Baguette Bread", emoji: "🥖"),
    EmojiObject(keyWord: "Cheese Wedge", emoji: "🧀"),
    EmojiObject(keyWord: "Egg", emoji: "🥚"),
    EmojiObject(keyWord: "Fried Egg", emoji: "🍳"),
    EmojiObject(keyWord: "Bacon", emoji: "🥓"),
    EmojiObject(keyWord: "Pancakes", emoji: "🥞"),
    EmojiObject(keyWord: "Shrimp", emoji: "🍤"),
    EmojiObject(keyWord: "Poultry Leg", emoji: "🍗"),
    EmojiObject(keyWord: "Meat on Bone", emoji: "🍖"),
    EmojiObject(keyWord: "Pizza", emoji: "🍕"),
    EmojiObject(keyWord: "Hot Dog", emoji: "🌭"),
    EmojiObject(keyWord: "Hamburger", emoji: "🍔"),
    EmojiObject(keyWord: "French Fries", emoji: "🍟"),
    EmojiObject(keyWord: "Stuffed Flatbread", emoji: "🥙"),
    EmojiObject(keyWord: "Taco", emoji: "🌮"),
    EmojiObject(keyWord: "Burrito", emoji: "🌯"),
    EmojiObject(keyWord: "Green Salad", emoji: "🥗"),
    EmojiObject(keyWord: "Shallow Pan of Food", emoji: "🥘"),
    EmojiObject(keyWord: "Spaghetti", emoji: "🍝"),
    EmojiObject(keyWord: "Ramen", emoji: "🍜"),
    EmojiObject(keyWord: "Stew", emoji: "🍲"),
    EmojiObject(keyWord: "Fish Cake with Swirl", emoji: "🍥"),
    EmojiObject(keyWord: "Sushi", emoji: "🍣"),
    EmojiObject(keyWord: "Bento Box", emoji: "🍱"),
    EmojiObject(keyWord: "Curry Rice", emoji: "🍛"),
    EmojiObject(keyWord: "Rice", emoji: "🍚"),
    EmojiObject(keyWord: "Rice Cracker", emoji: "🍘"),
    EmojiObject(keyWord: "Oden", emoji: "🍢"),
    EmojiObject(keyWord: "Dango", emoji: "🍡"),
    EmojiObject(keyWord: "Shaved Ice", emoji: "🍧"),
    EmojiObject(keyWord: "Ice Cream", emoji: "🍨"),
    EmojiObject(keyWord: "Birthday Cake", emoji: "🍰"),
    EmojiObject(keyWord: "Shortcake", emoji: "🎂"),
    EmojiObject(keyWord: "Custard", emoji: "🍮"),
    EmojiObject(keyWord: "Candy", emoji: "🍭"),
    EmojiObject(keyWord: "Lollipop", emoji: "🍬"),
    EmojiObject(keyWord: "Chocolate Bar", emoji: "🍫"),
    EmojiObject(keyWord: "Popcorn", emoji: "🍿"),
    EmojiObject(keyWord: "Doughnut", emoji: "🍩"),
    EmojiObject(keyWord: "Cookie", emoji: "🍪"),
    EmojiObject(keyWord: "Glass of Milk", emoji: "🥛"),
    EmojiObject(keyWord: "Baby Bottle", emoji: "🍼"),
    EmojiObject(keyWord: "Hot Beverage", emoji: "☕️"),
    EmojiObject(keyWord: "Teacup Without Handle", emoji: "🍵"),
    EmojiObject(keyWord: "Sake", emoji: "🍶"),
    EmojiObject(keyWord: "Beer Mug", emoji: "🍺"),
    EmojiObject(keyWord: "Clinking Beer Mugs", emoji: "🍻"),
    EmojiObject(keyWord: "Clinking Glasses", emoji: "🥂"),
    EmojiObject(keyWord: "Wine Glass", emoji: "🍷"),
    EmojiObject(keyWord: "Cocktail Glass", emoji: "🍸"),
    EmojiObject(keyWord: "Tropical Drink", emoji: "🍹"),
    EmojiObject(keyWord: "Bottle with Popping Cork", emoji: "🍾"),
    EmojiObject(keyWord: "Fork and Knife with Plate", emoji: "🍽"),
    EmojiObject(keyWord: "Spoon", emoji: "🥄"),
    EmojiObject(keyWord: "Bowl with Straw", emoji: "🥥"),
    EmojiObject(keyWord: "Broccoli", emoji: "🥦"),
    EmojiObject(keyWord: "Garlic", emoji: "🥖"),
    EmojiObject(keyWord: "Cut of Meat", emoji: "🥩"),
    EmojiObject(keyWord: "Sandwich", emoji: "🥪"),
    EmojiObject(keyWord: "Bowl with Spoon", emoji: "🥣"),
    EmojiObject(keyWord: "Canned Food", emoji: "🥫"),
    EmojiObject(keyWord: "Dumpling", emoji: "🥟"),
    EmojiObject(keyWord: "Fortune Cookie", emoji: "🥠"),
    EmojiObject(keyWord: "Takeout Box", emoji: "🥡"),
    EmojiObject(keyWord: "Pie", emoji: "🥧"),
    EmojiObject(keyWord: "Beverage Box", emoji: "🥤"),
    EmojiObject(keyWord: "Chopsticks", emoji: "🥢")
]
