//
//  language.swift
//  Swift_UIKit_ChatApp
//
//  Created by Al-Tameemi Hayder on 1.6.2023.
//

import UIKit

struct Language {
    static var ok = "OK"
    static var chat = "Chat"
    static var chats = "Chats";
    static var there_are_no_active_chats_you_have_tap_the = "There are no active chats you have. Tap the"
    static var button_to_start_a_new_chat = "button to start a new chat"
    static var icon_to_start_a_new_chat = "icon to start a new chat"
    static var there_are_no_archived_chats_you_have = "There are no archived chats you have"
    static var all_of_your_chats_are_archived_tap_the = "All of your chats are archived. Tap the"
    static var archived_chats = "Archived Chats";
    
    static var these_chats_stay_archived_even_when_new_messages_are_received = "These archived chats stay archived even when new messages are received"
    static var edit = "Edit"
    static var cancel = "Cancel"
    static var done = "Done"
    static var delete = "Delete"
    static var delete_chat = "Delete Chat"
    static var delete_chat_with = "Delete chat with"
    static var delete_for_me = "Delete for me"
    static var delete_for_all = "Delete for all"
    static var archive = "Archive"
    static var archive_chat = "Archive Chat"
    static var unarchive = "Unarchive"
    static var unarchive_chat = "Unarchive chat"
    static var read = "Read"
    static var unread = "Unread"
    static var mute = "Mute"
    static var unmute = "Unmute"
    static var pin = "Pin"
    static var unpin = "Unpin"
    static var read_all = "Read All"
    static var selected = "Selected"
    static var new_chat = "New Chat"
    static var last_seen = "last seen"
    static var new_qroup = "New Group"
    static var new_contact = "New Contact"
    static var back = "Back"
    static var group_members = "Group Members"
    static var next = "Next"
    static var users = "Users"
    static var search = "Search"
    static var search_results = "Search Results"
    static var create = "Create"
    static var group_info = "Group Info"
    static var group_name = "Group Name"
    static var personal_and_group_messages_are_end_to_end_encrypted = "Group chats are end-to-end encrypted"
    static var up_to = "Up to"
    static var membersSmallLetter = "members"
    static var auto_disapear_messages = "Auto-Disapear Messages"
    static var automatically_disapear_messages_in_this_group_after_period_of_time = "Automatically disapear messages in this group after period of time"
    static var off = "Off"
    static var twenty_four_hours = "24 Hours"
    static var seven_days = "7 Days"
    static var thirty_days = "30 Days"
    static var open_camera = "Open Camera"
    static var choose_image = "Choose Image"
    static var emoji_image = "Emoji Image"
    static var search_web = "Search Web"
    static var members = "members"
    static var mark_as_read = "Mark as Read"
    static var mark_as_unread = "Mark as Unread"
    static var message = "Message"
    static var today = "Today"
    static var photos = "photos"
    static var camera = "Camera"
    static var file = "file"
    static var gallery = "Gallery"
    static var map = "Map"
    static var poll = "Poll"
    static var user = "User"
    static var Couldnt_download_image_check_your_internet_connection_and_try_again = "Couldn't download image. Check your internet connection and try again."
    static var create_chat = "Creat Chat"
    static var new = "New"
    static var something_went_wrong = "Something went wrong"
    static var erorr_please_try_again_later = "Error please try again later"
    static var connection_error = "Connection error"
    static var no_internet_connection_please_check_your_network_settings = "No internet connection. Please check your network settings"
    static var connecting = "Connecting"
    static var loading = "Loading"
    static var updating = "Updating"
    static var waiting_for_network = "Waiting for network"
    static var you_have_created_a_group = "You have created a group"
    static var KB = "KB"
    static var reply = "Reply"
    static var copy = "Copy"
    static var forward = "Forward"
    static var select = "Select"
    static var no_emoji_found = "No emoji found"

}
