//
//  File.swift
//  Swift_UIKit_ChatApp
//
//  Created by Al-Tameemi Hayder on 26.10.2023.
//

let activityEmojis = [
    EmojiObject(keyWord: "Football", emoji: "⚽️"),
    EmojiObject(keyWord: "Basketball", emoji: "🏀"),
    EmojiObject(keyWord: "American Football", emoji: "🏈"),
    EmojiObject(keyWord: "Baseball", emoji: "⚾️"),
    EmojiObject(keyWord: "Tennis", emoji: "🎾"),
    EmojiObject(keyWord: "Volleyball", emoji: "🏐"),
    EmojiObject(keyWord: "Rugby", emoji: "🏉"),
    EmojiObject(keyWord: "Billiards", emoji: "🎱"),
    EmojiObject(keyWord: "Table Tennis", emoji: "🏓"),
    EmojiObject(keyWord: "Badminton", emoji: "🏸"),
    EmojiObject(keyWord: "Ice Hockey", emoji: "🥅"),
    EmojiObject(keyWord: "Field Hockey", emoji: "🏒"),
    EmojiObject(keyWord: "Hockey", emoji: "🏑"),
    EmojiObject(keyWord: "Cricket", emoji: "🏏"),
    EmojiObject(keyWord: "Golf", emoji: "⛳️"),
    EmojiObject(keyWord: "Archery", emoji: "🏹"),
    EmojiObject(keyWord: "Fishing", emoji: "🎣"),
    EmojiObject(keyWord: "Boxing", emoji: "🥊"),
    EmojiObject(keyWord: "Karate", emoji: "🥋"),
    EmojiObject(keyWord: "Figure Skating", emoji: "⛸"),
    EmojiObject(keyWord: "Skiing", emoji: "🎿"),
    EmojiObject(keyWord: "Snowboarding", emoji: "🏂"),
    EmojiObject(keyWord: "Weightlifting", emoji: "🏋️‍♀️"),
    EmojiObject(keyWord: "Weightlifting", emoji: "🏋"),
    EmojiObject(keyWord: "Fencing", emoji: "🤺"),
    EmojiObject(keyWord: "Wrestling (♀)", emoji: "🤼‍♀"),
    EmojiObject(keyWord: "Wrestling (♂)", emoji: "🤼‍♂"),
    EmojiObject(keyWord: "Gymnastics (♀)", emoji: "🤸‍♀"),
    EmojiObject(keyWord: "Gymnastics (♂)", emoji: "🤸‍♂"),
    EmojiObject(keyWord: "Basketball (♀)", emoji: "⛹️‍♀️"),
    EmojiObject(keyWord: "Basketball (♂)", emoji: "⛹"),
    EmojiObject(keyWord: "Handball (♀)", emoji: "🤾‍♀"),
    EmojiObject(keyWord: "Handball (♂)", emoji: "🤾‍♂"),
    EmojiObject(keyWord: "Golf (♀)", emoji: "🏌️‍♀️"),
    EmojiObject(keyWord: "Golf (♂)", emoji: "🏌"),
    EmojiObject(keyWord: "Surfing (♀)", emoji: "🏄‍♀"),
    EmojiObject(keyWord: "Surfing (♂)", emoji: "🏄"),
    EmojiObject(keyWord: "Swimming (♀)", emoji: "🏊‍♀"),
    EmojiObject(keyWord: "Swimming (♂)", emoji: "🏊"),
    EmojiObject(keyWord: "Water Polo (♀)", emoji: "🤽‍♀"),
    EmojiObject(keyWord: "Water Polo (♂)", emoji: "🤽‍♂"),
    EmojiObject(keyWord: "Rowing (♀)", emoji: "🚣‍♀"),
    EmojiObject(keyWord: "Rowing (♂)", emoji: "🚣"),
    EmojiObject(keyWord: "Horse Racing", emoji: "🏇"),
    EmojiObject(keyWord: "Cycling (♀)", emoji: "🚴‍♀"),
    EmojiObject(keyWord: "Cycling (♂)", emoji: "🚴"),
    EmojiObject(keyWord: "Mountain Biking (♀)", emoji: "🚵‍♀"),
    EmojiObject(keyWord: "Mountain Biking (♂)", emoji: "🚵"),
    EmojiObject(keyWord: "Running", emoji: "🎽"),
    EmojiObject(keyWord: "Sports Medal", emoji: "🏅"),
    EmojiObject(keyWord: "Sports Medal (1st)", emoji: "🎖"),
    EmojiObject(keyWord: "Sports Medal (2nd)", emoji: "🥇"),
    EmojiObject(keyWord: "Sports Medal (3rd)", emoji: "🥈"),
    EmojiObject(keyWord: "Trophy", emoji: "🥉"),
    EmojiObject(keyWord: "Rosette", emoji: "🏆"),
    EmojiObject(keyWord: "Ticket", emoji: "🏵"),
    EmojiObject(keyWord: "Circus Tent", emoji: "🎗"),
    EmojiObject(keyWord: "Juggling (♀)", emoji: "🎫"),
    EmojiObject(keyWord: "Juggling (♂)", emoji: "🎟"),
    EmojiObject(keyWord: "Theater", emoji: "🎪"),
    EmojiObject(keyWord: "Artist Palette", emoji: "🤹‍♀"),
    EmojiObject(keyWord: "Movie Camera", emoji: "🤹‍♂"),
    EmojiObject(keyWord: "Microphone", emoji: "🎭"),
    EmojiObject(keyWord: "Headphone", emoji: "🎨"),
    EmojiObject(keyWord: "Musical Score", emoji: "🎬"),
    EmojiObject(keyWord: "Musical Keyboard", emoji: "🎤"),
    EmojiObject(keyWord: "Drum", emoji: "🎧"),
    EmojiObject(keyWord: "Saxophone", emoji: "🎼"),
    EmojiObject(keyWord: "Trumpet", emoji: "🎹"),
    EmojiObject(keyWord: "Guitar", emoji: "🥁"),
    EmojiObject(keyWord: "Violin", emoji: "🎷"),
    EmojiObject(keyWord: "Game Die", emoji: "🎺"),
    EmojiObject(keyWord: "Bullseye", emoji: "🎸"),
    EmojiObject(keyWord: "Bowling", emoji: "🎻"),
    EmojiObject(keyWord: "Video Game", emoji: "🎲"),
    EmojiObject(keyWord: "Slot Machine", emoji: "🎯"),
    EmojiObject(keyWord: "Soccer Ball", emoji: "🎳"),
    EmojiObject(keyWord: "Weightlifting", emoji: "🎮"),
    EmojiObject(keyWord: "Skiing", emoji: "🎰")
]
