//
//  animalsAndNatureArray.swift
//  Swift_UIKit_ChatApp
//
//  Created by Al-Tameemi Hayder on 26.10.2023.
//

let animalsAndNatureEmojis: [EmojiObject] = [
    EmojiObject(keyWord: "Dog", emoji: "🐶"),
    EmojiObject(keyWord: "Cat", emoji: "🐱"),
    EmojiObject(keyWord: "Mouse", emoji: "🐭"),
    EmojiObject(keyWord: "Hamster", emoji: "🐹"),
    EmojiObject(keyWord: "Rabbit", emoji: "🐰"),
    EmojiObject(keyWord: "Fox", emoji: "🦊"),
    EmojiObject(keyWord: "Bear", emoji: "🐻"),
    EmojiObject(keyWord: "Panda", emoji: "🐼"),
    EmojiObject(keyWord: "Koala", emoji: "🐨"),
    EmojiObject(keyWord: "Tiger", emoji: "🐯"),
    EmojiObject(keyWord: "Lion", emoji: "🦁"),
    EmojiObject(keyWord: "Cow", emoji: "🐮"),
    EmojiObject(keyWord: "Pig", emoji: "🐷"),
    EmojiObject(keyWord: "Pig Snout", emoji: "🐽"),
    EmojiObject(keyWord: "Frog", emoji: "🐸"),
    EmojiObject(keyWord: "Monkey Face", emoji: "🐵"),
    EmojiObject(keyWord: "See-No-Evil Monkey", emoji: "🙈"),
    EmojiObject(keyWord: "Hear-No-Evil Monkey", emoji: "🙉"),
    EmojiObject(keyWord: "Speak-No-Evil Monkey", emoji: "🙊"),
    EmojiObject(keyWord: "Monkey", emoji: "🐒"),
    EmojiObject(keyWord: "Rooster", emoji: "🐔"),
    EmojiObject(keyWord: "Penguin", emoji: "🐧"),
    EmojiObject(keyWord: "Bird", emoji: "🐦"),
    EmojiObject(keyWord: "Baby Chick", emoji: "🐤"),
    EmojiObject(keyWord: "Front-Facing Baby Chick", emoji: "🐣"),
    EmojiObject(keyWord: "Hatching Chick", emoji: "🐥"),
    EmojiObject(keyWord: "Duck", emoji: "🦆"),
    EmojiObject(keyWord: "Eagle", emoji: "🦅"),
    EmojiObject(keyWord: "Owl", emoji: "🦉"),
    EmojiObject(keyWord: "Bat", emoji: "🦇"),
    EmojiObject(keyWord: "Wolf", emoji: "🐺"),
    EmojiObject(keyWord: "Boar", emoji: "🐗"),
    EmojiObject(keyWord: "Horse", emoji: "🐴"),
    EmojiObject(keyWord: "Unicorn", emoji: "🦄"),
    EmojiObject(keyWord: "Honeybee", emoji: "🐝"),
    EmojiObject(keyWord: "Bug", emoji: "🐛"),
    EmojiObject(keyWord: "Butterfly", emoji: "🦋"),
    EmojiObject(keyWord: "Snail", emoji: "🐌"),
    EmojiObject(keyWord: "Spiral Shell", emoji: "🐚"),
    EmojiObject(keyWord: "Lady Beetle", emoji: "🐞"),
    EmojiObject(keyWord: "Ant", emoji: "🐜"),
    EmojiObject(keyWord: "Spider", emoji: "🕷"),
    EmojiObject(keyWord: "Spider Web", emoji: "🕸"),
    EmojiObject(keyWord: "Turtle", emoji: "🐢"),
    EmojiObject(keyWord: "Snake", emoji: "🐍"),
    EmojiObject(keyWord: "Lizard", emoji: "🦎"),
    EmojiObject(keyWord: "Scorpion", emoji: "🦂"),
    EmojiObject(keyWord: "Crab", emoji: "🦀"),
    EmojiObject(keyWord: "Shrimp", emoji: "🦑"),
    EmojiObject(keyWord: "Squid", emoji: "🐙"),
    EmojiObject(keyWord: "Fish", emoji: "🐠"),
    EmojiObject(keyWord: "Tropical Fish", emoji: "🐟"),
    EmojiObject(keyWord: "Blowfish", emoji: "🐡"),
    EmojiObject(keyWord: "Dolphin", emoji: "🐬"),
    EmojiObject(keyWord: "Shark", emoji: "🦈"),
    EmojiObject(keyWord: "Whale", emoji: "🐳"),
    EmojiObject(keyWord: "Whale Shark", emoji: "🐋"),
    EmojiObject(keyWord: "Crocodile", emoji: "🐊"),
    EmojiObject(keyWord: "Leopard", emoji: "🐆"),
    EmojiObject(keyWord: "Tiger", emoji: "🐅"),
    EmojiObject(keyWord: "Water Buffalo", emoji: "🐃"),
    EmojiObject(keyWord: "Ox", emoji: "🐂"),
    EmojiObject(keyWord: "Cow", emoji: "🐄"),
    EmojiObject(keyWord: "Deer", emoji: "🦌"),
    EmojiObject(keyWord: "Camel", emoji: "🐪"),
    EmojiObject(keyWord: "Two-Hump Camel", emoji: "🐫"),
    EmojiObject(keyWord: "Elephant", emoji: "🐘"),
    EmojiObject(keyWord: "Rhinoceros", emoji: "🦏"),
    EmojiObject(keyWord: "Gorilla", emoji: "🦍"),
    EmojiObject(keyWord: "Racehorse", emoji: "🐎"),
    EmojiObject(keyWord: "Goat", emoji: "🐖"),
    EmojiObject(keyWord: "Ram", emoji: "🐐"),
    EmojiObject(keyWord: "Sheep", emoji: "🐏"),
    EmojiObject(keyWord: "Lamb", emoji: "🐑"),
    EmojiObject(keyWord: "Dog", emoji: "🐕"),
    EmojiObject(keyWord: "Poodle", emoji: "🐩"),
    EmojiObject(keyWord: "Cat", emoji: "🐈"),
    EmojiObject(keyWord: "Turkey", emoji: "🦃"),
    EmojiObject(keyWord: "Dove", emoji: "🕊"),
    EmojiObject(keyWord: "Rabbit", emoji: "🐇"),
    EmojiObject(keyWord: "Mouse", emoji: "🐁"),
    EmojiObject(keyWord: "Rat", emoji: "🐀"),
    EmojiObject(keyWord: "Chipmunk", emoji: "🐿"),
    EmojiObject(keyWord: "Paw Prints", emoji: "🐾"),
    EmojiObject(keyWord: "Dragon Face", emoji: "🐉"),
    EmojiObject(keyWord: "Dragon", emoji: "🐲"),
    EmojiObject(keyWord: "Cactus", emoji: "🌵"),
    EmojiObject(keyWord: "Christmas Tree", emoji: "🎄"),
    EmojiObject(keyWord: "Evergreen Tree", emoji: "🌲"),
    EmojiObject(keyWord: "Deciduous Tree", emoji: "🌳"),
    EmojiObject(keyWord: "Palm Tree", emoji: "🌴"),
    EmojiObject(keyWord: "Seedling", emoji: "🌱"),
    EmojiObject(keyWord: "Herb", emoji: "🌿"),
    EmojiObject(keyWord: "Shamrock", emoji: "☘️"),
    EmojiObject(keyWord: "Four Leaf Clover", emoji: "🍀"),
    EmojiObject(keyWord: "Bamboo", emoji: "🎍"),
    EmojiObject(keyWord: "Tanabata Tree", emoji: "🎋"),
    EmojiObject(keyWord: "Leaf Fluttering in Wind", emoji: "🍃"),
    EmojiObject(keyWord: "Fallen Leaf", emoji: "🍂"),
    EmojiObject(keyWord: "Maple Leaf", emoji: "🍁"),
    EmojiObject(keyWord: "Mushroom", emoji: "🍄"),
    EmojiObject(keyWord: "Bouquet", emoji: "💐"),
    EmojiObject(keyWord: "Tulip", emoji: "🌷"),
    EmojiObject(keyWord: "Rose", emoji: "🌹"),
    EmojiObject(keyWord: "Wilted Flower", emoji: "🥀"),
    EmojiObject(keyWord: "Hibiscus", emoji: "🌺"),
    EmojiObject(keyWord: "Sunflower", emoji: "🌻"),
    EmojiObject(keyWord: "Blossom", emoji: "🌼"),
    EmojiObject(keyWord: "Cherry Blossom", emoji: "🌸"),
    EmojiObject(keyWord: "Earth Globe Europe-Africa", emoji: "🌍"),
    EmojiObject(keyWord: "Earth Globe Americas", emoji: "🌎"),
    EmojiObject(keyWord: "Earth Globe Asia-Australia", emoji: "🌏"),
    EmojiObject(keyWord: "Full Moon", emoji: "🌕"),
    EmojiObject(keyWord: "Waning Gibbous Moon", emoji: "🌖"),
    EmojiObject(keyWord: "Last Quarter Moon", emoji: "🌗"),
    EmojiObject(keyWord: "Waning Crescent Moon", emoji: "🌘"),
    EmojiObject(keyWord: "New Moon", emoji: "🌑"),
    EmojiObject(keyWord: "Waxing Crescent Moon", emoji: "🌒"),
    EmojiObject(keyWord: "First Quarter Moon", emoji: "🌓"),
    EmojiObject(keyWord: "Waxing Gibbous Moon", emoji: "🌔"),
    EmojiObject(keyWord: "Full Moon Face", emoji: "🌝"),
    EmojiObject(keyWord: "Sun with Face", emoji: "🌞"),
    EmojiObject(keyWord: "First Quarter Moon Face", emoji: "🌛"),
    EmojiObject(keyWord: "Last Quarter Moon Face", emoji: "🌜"),
    EmojiObject(keyWord: "Crescent Moon", emoji: "🌙"),
    EmojiObject(keyWord: "Star", emoji: "⭐️"),
    EmojiObject(keyWord: "Glowing Star", emoji: "🌟"),
    EmojiObject(keyWord: "Shooting Star", emoji: "✨"),
    EmojiObject(keyWord: "High Voltage", emoji: "⚡️"),
    EmojiObject(keyWord: "Fire", emoji: "🔥"),
    EmojiObject(keyWord: "Dizzy", emoji: "💫"),
    EmojiObject(keyWord: "Sparkles", emoji: "✨"),
    EmojiObject(keyWord: "Comet", emoji: "☄"),
    EmojiObject(keyWord: "Sun", emoji: "☀️"),
    EmojiObject(keyWord: "Sun Behind Small Cloud", emoji: "🌤"),
    EmojiObject(keyWord: "Sun Behind Large Cloud", emoji: "⛅"),
    EmojiObject(keyWord: "Sun Behind Rain Cloud", emoji: "🌦"),
    EmojiObject(keyWord: "Sun Behind Cloud", emoji: "🌥"),
    EmojiObject(keyWord: "Rainbow", emoji: "🌈"),
    EmojiObject(keyWord: "Cloud", emoji: "☁️"),
    EmojiObject(keyWord: "Rain", emoji: "🌧"),
    EmojiObject(keyWord: "Thunder Cloud and Rain", emoji: "⛈"),
    EmojiObject(keyWord: "Lightning", emoji: "🌩"),
    EmojiObject(keyWord: "Snow", emoji: "🌨"),
    EmojiObject(keyWord: "Snowman", emoji: "☃️"),
    EmojiObject(keyWord: "Snowflake", emoji: "❄️"),
    EmojiObject(keyWord: "Wind Face", emoji: "🌬"),
    EmojiObject(keyWord: "Wind Blowing Face", emoji: "💨"),
    EmojiObject(keyWord: "Tornado", emoji: "🌪"),
    EmojiObject(keyWord: "Fog", emoji: "🌫"),
    EmojiObject(keyWord: "Ocean Wave", emoji: "🌊"),
    EmojiObject(keyWord: "Droplet", emoji: "💧"),
    EmojiObject(keyWord: "Splash", emoji: "💦"),
    EmojiObject(keyWord: "Umbrella", emoji: "☔️"),
    EmojiObject(keyWord: "Zebra", emoji: "🦓"),
    EmojiObject(keyWord: "Giraffe", emoji: "🦒"),
    EmojiObject(keyWord: "Hedgehog", emoji: "🦔"),
    EmojiObject(keyWord: "Sauropod", emoji: "🦕"),
    EmojiObject(keyWord: "T-Rex", emoji: "🦖")
]
