//
//  SmilyAndPeople.swift
//  Swift_UIKit_ChatApp
//
//  Created by Al-Tameemi Hayder on 26.10.2023.
//

let smilyAndPeopleEmojis: [EmojiObject] = [
    EmojiObject(keyWord: "Happy laughing Grinning Face", emoji: "😀"),
    EmojiObject(keyWord: "Happy laughing Grinning Face with Big Eyes", emoji: "😃"),
    EmojiObject(keyWord: "Happy laughing Grinning Face with Smiling Eyes", emoji: "😄"),
    EmojiObject(keyWord: "Happy laughing Beaming Face with Smiling Eyes", emoji: "😁"),
    EmojiObject(keyWord: "Happy laughing Grinning Squinting Face", emoji: "😆"),
    EmojiObject(keyWord: "Happy laughing Grinning Face with Sweat", emoji: "😅"),
    EmojiObject(keyWord: "Happy laughing Face with Tears of Joy", emoji: "😂"),
    EmojiObject(keyWord: "Happy laughing Rolling on the Floor Laughing", emoji: "🤣"),
    EmojiObject(keyWord: "Happy Smiling Face with Smiling Eyes", emoji: "☺️"),
    EmojiObject(keyWord: "Happy Smiling Face with Halo", emoji: "😇"),
    EmojiObject(keyWord: "Happy Slightly Smiling Face", emoji: "🙂"),
    EmojiObject(keyWord: "Upside-Down Face", emoji: "🙃"),
    EmojiObject(keyWord: "Winking Face", emoji: "😉"),
    EmojiObject(keyWord: "Smiling Face with Smiling Eyes", emoji: "😌"),
    EmojiObject(keyWord: "love Heart Eyes", emoji: "😍"),
    EmojiObject(keyWord: "Face Blowing a Kiss", emoji: "😘"),
    EmojiObject(keyWord: "Kissing Face", emoji: "😗"),
    EmojiObject(keyWord: "Kissing Face with Closed Eyes", emoji: "😙"),
    EmojiObject(keyWord: "Kissing Face with Smiling Eyes", emoji: "😚"),
    EmojiObject(keyWord: "Face with Tongue", emoji: "😛"),
    EmojiObject(keyWord: "Money-Mouth Face", emoji: "🤑"),
    EmojiObject(keyWord: "Hugging Face", emoji: "🤗"),
    EmojiObject(keyWord: "Nerd Face", emoji: "🤓"),
    EmojiObject(keyWord: "Smiling Face with Sunglasses", emoji: "😎"),
    EmojiObject(keyWord: "Clown Face", emoji: "🤡"),
    EmojiObject(keyWord: "Cowboy Hat Face", emoji: "🤠"),
    EmojiObject(keyWord: "Smirking Face", emoji: "😏"),
    EmojiObject(keyWord: "Unamused Face", emoji: "😒"),
    EmojiObject(keyWord: "Disappointed Face", emoji: "😞"),
    EmojiObject(keyWord: "Pensive Face", emoji: "😔"),
    EmojiObject(keyWord: "Confused Face", emoji: "😟"),
    EmojiObject(keyWord: "Slightly Frowning Face", emoji: "😕"),
    EmojiObject(keyWord: "Frowning Face", emoji: "🙁"),
    EmojiObject(keyWord: "Slightly Frowning Face", emoji: "☹️"),
    EmojiObject(keyWord: "Persevering Face", emoji: "😣"),
    EmojiObject(keyWord: "Confounded Face", emoji: "😖"),
    EmojiObject(keyWord: "Tired Face", emoji: "😫"),
    EmojiObject(keyWord: "Weary Face", emoji: "😩"),
    EmojiObject(keyWord: "Face with Steam from Nose", emoji: "😤"),
    EmojiObject(keyWord: "Angry Face", emoji: "😠"),
    EmojiObject(keyWord: "Pouting Face", emoji: "😡"),
    EmojiObject(keyWord: "Face Without Mouth", emoji: "😶"),
    EmojiObject(keyWord: "Neutral Face", emoji: "😐"),
    EmojiObject(keyWord: "Expressionless Face", emoji: "😑"),
    EmojiObject(keyWord: "Hushed Face", emoji: "😯"),
    EmojiObject(keyWord: "Frowning Face with Open Mouth", emoji: "😦"),
    EmojiObject(keyWord: "Anguished Face", emoji: "😧"),
    EmojiObject(keyWord: "Frowning Face with Open Mouth", emoji: "😮"),
    EmojiObject(keyWord: "Face with Cold Sweat", emoji: "😰"),
    EmojiObject(keyWord: "Disappointed but Relieved Face", emoji: "😥"),
    EmojiObject(keyWord: "Face with Open Mouth", emoji: "🤤"),
    EmojiObject(keyWord: "Loudly Crying Face", emoji: "😭"),
    EmojiObject(keyWord: "Crying Face", emoji: "😓"),
    EmojiObject(keyWord: "Sleepy Face", emoji: "😪"),
    EmojiObject(keyWord: "Sleeping Face", emoji: "😴"),
    EmojiObject(keyWord: "Face with Rolling Eyes", emoji: "🙄"),
    EmojiObject(keyWord: "Thinking Face", emoji: "🤔"),
    EmojiObject(keyWord: "Face with Hand Over Mouth", emoji: "🤭"),
    EmojiObject(keyWord: "Face with Monocle", emoji: "🧐"),
    EmojiObject(keyWord: "Face with Symbols on Mouth", emoji: "🤫"),
    EmojiObject(keyWord: "Face with Thermometer", emoji: "🤒"),
    EmojiObject(keyWord: "Face with Head-Bandage", emoji: "🤕"),
    EmojiObject(keyWord: "Face with Medical Mask", emoji: "😷"),
    EmojiObject(keyWord: "Face with Thermometer", emoji: "🤒"),
    EmojiObject(keyWord: "Face with Head-Bandage", emoji: "🤕"),
    EmojiObject(keyWord: "Smiling Face with Horns", emoji: "😈"),
    EmojiObject(keyWord: "Angry Face with Horns", emoji: "👿"),
    EmojiObject(keyWord: "Ogre", emoji: "👹"),
    EmojiObject(keyWord: "Goblin", emoji: "👺"),
    EmojiObject(keyWord: "Pile of Poo", emoji: "💩"),
    EmojiObject(keyWord: "Ghost", emoji: "👻"),
    EmojiObject(keyWord: "Skull and Crossbones", emoji: "💀"),
    EmojiObject(keyWord: "Skull and Crossbones", emoji: "☠️"),
    EmojiObject(keyWord: "Alien", emoji: "👽"),
    EmojiObject(keyWord: "Alien Monster", emoji: "👾"),
    EmojiObject(keyWord: "Robot Face", emoji: "🤖"),
    EmojiObject(keyWord: "Jack-O-Lantern", emoji: "🎃"),
    EmojiObject(keyWord: "Grinning Cat Face", emoji: "😺"),
    EmojiObject(keyWord: "Grinning Cat Face with Smiling Eyes", emoji: "😸"),
    EmojiObject(keyWord: "Cat Face with Tears of Joy", emoji: "😹"),
    EmojiObject(keyWord: "Smiling Cat Face with Heart-Eyes", emoji: "😻"),
    EmojiObject(keyWord: "Cat Face with Wry Smile", emoji: "😼"),
    EmojiObject(keyWord: "Kissing Cat Face", emoji: "😽"),
    EmojiObject(keyWord: "Weary Cat Face", emoji: "🙀"),
    EmojiObject(keyWord: "Crying Cat Face", emoji: "😿"),
    EmojiObject(keyWord: "Pouting Cat Face", emoji: "😾"),
    EmojiObject(keyWord: "Open Hands", emoji: "👐"),
    EmojiObject(keyWord: "Person Raising Both Hands in Celebration", emoji: "🙌"),
    EmojiObject(keyWord: "Clapping Hands", emoji: "👏"),
    EmojiObject(keyWord: "Person with Folded Hands", emoji: "🙏"),
    EmojiObject(keyWord: "Handshake", emoji: "🤝"),
    EmojiObject(keyWord: "Thumbs Up", emoji: "👍"),
    EmojiObject(keyWord: "Thumbs Down", emoji: "👎"),
    EmojiObject(keyWord: "Raised Fist", emoji: "👊"),
    EmojiObject(keyWord: "Oncoming Fist", emoji: "✊"),
    EmojiObject(keyWord: "Left-Facing Fist", emoji: "🤛"),
    EmojiObject(keyWord: "Right-Facing Fist", emoji: "🤜"),
    EmojiObject(keyWord: "Crossed Fingers", emoji: "🤞"),
    EmojiObject(keyWord: "Victory Hand", emoji: "✌️"),
    EmojiObject(keyWord: "Sign of the Horns", emoji: "🤘"),
    EmojiObject(keyWord: "OK Hand", emoji: "👌"),
    EmojiObject(keyWord: "Backhand Index Pointing Left", emoji: "👈"),
    EmojiObject(keyWord: "Backhand Index Pointing Right", emoji: "👉"),
    EmojiObject(keyWord: "Backhand Index Pointing Up", emoji: "👆"),
    EmojiObject(keyWord: "Backhand Index Pointing Down", emoji: "👇"),
    EmojiObject(keyWord: "Index Pointing Up", emoji: "☝️"),
    EmojiObject(keyWord: "Raised Hand", emoji: "✋"),
    EmojiObject(keyWord: "Raised Back of Hand", emoji: "🤚"),
    EmojiObject(keyWord: "Hand with Fingers Splayed", emoji: "🖐"),
    EmojiObject(keyWord: "Vulcan Salute", emoji: "🖖"),
    EmojiObject(keyWord: "Waving Hand", emoji: "👋"),
    EmojiObject(keyWord: "Call Me Hand", emoji: "🤙"),
    EmojiObject(keyWord: "Flexed Biceps", emoji: "💪"),
    EmojiObject(keyWord: "Middle Finger", emoji: "🖕"),
    EmojiObject(keyWord: "Writing Hand", emoji: "✍️"),
    EmojiObject(keyWord: "Selfie", emoji: "🤳"),
    EmojiObject(keyWord: "Nail Polish", emoji: "💅"),
    EmojiObject(keyWord: "Ring", emoji: "💍"),
    EmojiObject(keyWord: "Lipstick", emoji: "💄"),
    EmojiObject(keyWord: "Kiss Mark", emoji: "💋"),
    EmojiObject(keyWord: "Mouth", emoji: "👄"),
    EmojiObject(keyWord: "Tongue", emoji: "👅"),
    EmojiObject(keyWord: "Ear", emoji: "👂"),
    EmojiObject(keyWord: "Nose", emoji: "👃"),
    EmojiObject(keyWord: "Footprints", emoji: "👣"),
    EmojiObject(keyWord: "Eye", emoji: "👁"),
    EmojiObject(keyWord: "Eyes", emoji: "👀"),
    EmojiObject(keyWord: "Brain", emoji: "🧠"),
    EmojiObject(keyWord: "Speaking Head", emoji: "🗣"),
    EmojiObject(keyWord: "Bust in Silhouette", emoji: "👤"),
    EmojiObject(keyWord: "Busts in Silhouette", emoji: "👥"),
    EmojiObject(keyWord: "Baby", emoji: "👶"),
    EmojiObject(keyWord: "Boy", emoji: "👦"),
    EmojiObject(keyWord: "Girl", emoji: "👧"),
    EmojiObject(keyWord: "Man", emoji: "👨"),
    EmojiObject(keyWord: "Woman", emoji: "👩"),
    EmojiObject(keyWord: "Blond-Haired Woman", emoji: "👱‍♀"),
    EmojiObject(keyWord: "Blond-Haired Man", emoji: "👱"),
    EmojiObject(keyWord: "Old Man", emoji: "👴"),
    EmojiObject(keyWord: "Old Woman", emoji: "👵"),
    EmojiObject(keyWord: "Older Man", emoji: "👲"),
    EmojiObject(keyWord: "Older Woman", emoji: "👳‍♀"),
    EmojiObject(keyWord: "Older Man", emoji: "👳"),
    EmojiObject(keyWord: "Police Woman", emoji: "👮‍♀"),
    EmojiObject(keyWord: "Police Officer", emoji: "👮"),
    EmojiObject(keyWord: "Construction Worker Woman", emoji: "👷‍♀"),
    EmojiObject(keyWord: "Construction Worker", emoji: "👷"),
    EmojiObject(keyWord: "Guard Woman", emoji: "💂‍♀"),
    EmojiObject(keyWord: "Guard", emoji: "💂"),
    EmojiObject(keyWord: "Detective Woman", emoji: "🕵️‍♀️"),
    EmojiObject(keyWord: "Detective", emoji: "🕵"),
    EmojiObject(keyWord: "Doctor Woman", emoji: "👩‍⚕"),
    EmojiObject(keyWord: "Doctor", emoji: "👨‍⚕"),
    EmojiObject(keyWord: "Farmer Woman", emoji: "👩‍🌾"),
    EmojiObject(keyWord: "Farmer", emoji: "👨‍🌾"),
    EmojiObject(keyWord: "Cook Woman", emoji: "👩‍🍳"),
    EmojiObject(keyWord: "Cook", emoji: "👨‍🍳"),
    EmojiObject(keyWord: "Graduate Woman", emoji: "👩‍🎓"),
    EmojiObject(keyWord: "Graduate", emoji: "👨‍🎓"),
    EmojiObject(keyWord: "Singer Woman", emoji: "👩‍🎤"),
    EmojiObject(keyWord: "Singer", emoji: "👨‍🎤"),
    EmojiObject(keyWord: "Teacher Woman", emoji: "👩‍🏫"),
    EmojiObject(keyWord: "Teacher", emoji: "👨‍🏫"),
    EmojiObject(keyWord: "Factory Worker Woman", emoji: "👩‍🏭"),
    EmojiObject(keyWord: "Factory Worker", emoji: "👨‍🏭"),
    EmojiObject(keyWord: "Technologist Woman", emoji: "👩‍💻"),
    EmojiObject(keyWord: "Technologist", emoji: "👨‍💻"),
    EmojiObject(keyWord: "Office Worker Woman", emoji: "👩‍💼"),
    EmojiObject(keyWord: "Office Worker", emoji: "👨‍💼"),
    EmojiObject(keyWord: "Mechanic Woman", emoji: "👩‍🔧"),
    EmojiObject(keyWord: "Mechanic", emoji: "👨‍🔧"),
    EmojiObject(keyWord: "Scientist Woman", emoji: "👩‍🔬"),
    EmojiObject(keyWord: "Scientist", emoji: "👨‍🔬"),
    EmojiObject(keyWord: "Artist Woman", emoji: "👩‍🎨"),
    EmojiObject(keyWord: "Artist", emoji: "👨‍🎨"),
    EmojiObject(keyWord: "Firefighter Woman", emoji: "👩‍🚒"),
    EmojiObject(keyWord: "Firefighter", emoji: "👨‍🚒"),
    EmojiObject(keyWord: "Pilot Woman", emoji: "👩‍✈"),
    EmojiObject(keyWord: "Pilot", emoji: "👨‍✈"),
    EmojiObject(keyWord: "Astronaut Woman", emoji: "👩‍🚀"),
    EmojiObject(keyWord: "Astronaut", emoji: "👨‍🚀"),
    EmojiObject(keyWord: "Judge Woman", emoji: "👩‍⚖"),
    EmojiObject(keyWord: "Judge", emoji: "👨‍⚖"),
    EmojiObject(keyWord: "Mrs. Claus", emoji: "🤶"),
    EmojiObject(keyWord: "Santa Claus", emoji: "🎅"),
    EmojiObject(keyWord: "Princess", emoji: "👸"),
    EmojiObject(keyWord: "Prince", emoji: "🤴"),
    EmojiObject(keyWord: "Bride with Veil", emoji: "👰"),
    EmojiObject(keyWord: "Man in Tuxedo", emoji: "🤵"),
    EmojiObject(keyWord: "Baby Angel", emoji: "👼"),
    EmojiObject(keyWord: "Pregnant Woman", emoji: "🤰"),
    EmojiObject(keyWord: "Person Bowing Deeply", emoji: "🙇‍♀"),
    EmojiObject(keyWord: "Person Bowing Deeply", emoji: "🙇"),
    EmojiObject(keyWord: "Person Tipping Hand", emoji: "💁"),
    EmojiObject(keyWord: "Person Tipping Hand", emoji: "💁‍♂"),
    EmojiObject(keyWord: "Person Gesturing NO", emoji: "🙅"),
    EmojiObject(keyWord: "Person Gesturing NO", emoji: "🙅‍♂"),
    EmojiObject(keyWord: "Person Gesturing OK", emoji: "🙆"),
    EmojiObject(keyWord: "Person Gesturing OK", emoji: "🙆‍♂"),
    EmojiObject(keyWord: "Person Raising Hand", emoji: "🙋"),
    EmojiObject(keyWord: "Person Raising Hand", emoji: "🙋‍♂"),
    EmojiObject(keyWord: "Person Facepalming", emoji: "🤦‍♀"),
    EmojiObject(keyWord: "Person Facepalming", emoji: "🤦‍♂"),
    EmojiObject(keyWord: "Person Shrugging", emoji: "🤷‍♀"),
    EmojiObject(keyWord: "Person Shrugging", emoji: "🤷‍♂"),
    EmojiObject(keyWord: "Person Pouting", emoji: "🙎"),
    EmojiObject(keyWord: "Person Pouting", emoji: "🙎‍♂"),
    EmojiObject(keyWord: "Person Frowning", emoji: "🙍"),
    EmojiObject(keyWord: "Person Frowning", emoji: "🙍‍♂"),
    EmojiObject(keyWord: "Person Getting Haircut", emoji: "💇"),
    EmojiObject(keyWord: "Person Getting Haircut", emoji: "💇‍♂"),
    EmojiObject(keyWord: "Person Getting Massage", emoji: "💆"),
    EmojiObject(keyWord: "Person Getting Massage", emoji: "💆‍♂"),
    EmojiObject(keyWord: "Man in Business Suit Levitating", emoji: "🕴"),
    EmojiObject(keyWord: "Dancer", emoji: "💃"),
    EmojiObject(keyWord: "Man Dancing", emoji: "🕺"),
    EmojiObject(keyWord: "People with Bunny Ears", emoji: "👯"),
    EmojiObject(keyWord: "People with Bunny Ears", emoji: "👯‍♂"),
    EmojiObject(keyWord: "Person Walking", emoji: "🚶‍♀"),
    EmojiObject(keyWord: "Person Walking", emoji: "🚶"),
    EmojiObject(keyWord: "Runner", emoji: "🏃‍♀"),
    EmojiObject(keyWord: "Runner", emoji: "🏃"),
    EmojiObject(keyWord: "Man and Woman Holding Hands", emoji: "👫"),
    EmojiObject(keyWord: "Two Women Holding Hands", emoji: "👭"),
    EmojiObject(keyWord: "Two Men Holding Hands", emoji: "👬"),
    EmojiObject(keyWord: "Love Couple with Heart", emoji: "💑"),
    EmojiObject(keyWord: "Couple with Two Women", emoji: "👩‍❤️‍👩"),
    EmojiObject(keyWord: "Love Couple with Two Men", emoji: "👨‍❤️‍👨"),
    EmojiObject(keyWord: "Love Kiss", emoji: "💏"),
    EmojiObject(keyWord: "Love Kiss Heart Woman, Woman", emoji: "👩‍❤️‍💋‍👩"),
    EmojiObject(keyWord: "Love Kiss Heart Man, Man", emoji: "👨‍❤️‍💋‍👨"),
    EmojiObject(keyWord: "Family", emoji: "👪"),
    EmojiObject(keyWord: "Family Woman, Woman, Girl", emoji: "👨‍👩‍👧"),
    EmojiObject(keyWord: "Family Woman, Woman, Boy", emoji: "👨‍👩‍👦"),
    EmojiObject(keyWord: "Family Woman, Woman, Boy, Boy", emoji: "👨‍👩‍👦‍👦"),
    EmojiObject(keyWord: "Family Woman, Woman, Girl, Girl", emoji: "👨‍👩‍👧‍👧"),
    EmojiObject(keyWord: "Family Woman, Boy", emoji: "👩‍👩‍👦"),
    EmojiObject(keyWord: "Family Woman, Girl", emoji: "👩‍👩‍👧"),
    EmojiObject(keyWord: "Family Woman, Girl, Girl", emoji: "👩‍👩‍👧‍👧"),
    EmojiObject(keyWord: "Family Woman, Boy, Boy", emoji: "👩‍👩‍👦‍👦"),
    EmojiObject(keyWord: "Family Woman, Girl, Boy", emoji: "👩‍👩‍👧‍👦"),
    EmojiObject(keyWord: "Family Man, Woman, Boy", emoji: "👨‍👨‍👦"),
    EmojiObject(keyWord: "Family Man, Woman, Girl", emoji: "👨‍👨‍👧"),
    EmojiObject(keyWord: "Family Man, Woman, Boy, Boy", emoji: "👨‍👨‍👦‍👦"),
    EmojiObject(keyWord: "Family Man, Woman, Girl, Girl", emoji: "👨‍👨‍👧‍👧"),
    EmojiObject(keyWord: "Family Man, Boy", emoji: "👨‍👨‍👦"),
    EmojiObject(keyWord: "Family Man, Girl", emoji: "👨‍👨‍👧"),
    EmojiObject(keyWord: "Family Man, Girl, Girl", emoji: "👨‍👨‍👧‍👧"),
    EmojiObject(keyWord: "Family Man, Boy, Boy", emoji: "👨‍👨‍👦‍👦"),
    EmojiObject(keyWord: "Family Man, Girl, Boy", emoji: "👨‍👨‍👧‍👦"),
    EmojiObject(keyWord: "Bikini", emoji: "👙"),
    EmojiObject(keyWord: "Woman's Clothes", emoji: "👚"),
    EmojiObject(keyWord: "T-Shirt", emoji: "👕"),
    EmojiObject(keyWord: "Necktie", emoji: "👔"),
    EmojiObject(keyWord: "Dress", emoji: "👗"),
    EmojiObject(keyWord: "Bikini", emoji: "👙"),
    EmojiObject(keyWord: "Woman's Sandal", emoji: "👡"),
    EmojiObject(keyWord: "High-Heeled Shoe", emoji: "👠"),
    EmojiObject(keyWord: "Woman's Boot", emoji: "👢"),
    EmojiObject(keyWord: "Man's Shoe", emoji: "👞"),
    EmojiObject(keyWord: "Running Shoe", emoji: "👟"),
    EmojiObject(keyWord: "Scarf", emoji: "🧣"),
    EmojiObject(keyWord: "Gloves", emoji: "🧤"),
    EmojiObject(keyWord: "Coat", emoji: "🧥"),
    EmojiObject(keyWord: "Socks", emoji: "🧦"),
    EmojiObject(keyWord: "Top Hat", emoji: "🎩"),
    EmojiObject(keyWord: "Graduation Cap", emoji: "🎓"),
    EmojiObject(keyWord: "Crown", emoji: "👑"),
    EmojiObject(keyWord: "Helmet with White Cross", emoji: "⛑"),
    EmojiObject(keyWord: "School Backpack", emoji: "🎒"),
    EmojiObject(keyWord: "Clutch Bag", emoji: "👝"),
    EmojiObject(keyWord: "Purse", emoji: "👛"),
    EmojiObject(keyWord: "Handbag", emoji: "👜"),
    EmojiObject(keyWord: "Briefcase", emoji: "💼"),
    EmojiObject(keyWord: "Eyeglasses", emoji: "👓"),
    EmojiObject(keyWord: "Dark Sunglasses", emoji: "🕶"),
    EmojiObject(keyWord: "Closed Umbrella", emoji: "🌂"),
    EmojiObject(keyWord: "Umbrella with Rain Drops", emoji: "☂️")
]
