language: swift
osx_image: xcode11.2
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - RUN_TESTS="YES"
    - BUILD_EXAMPLE="YES"
    - POD_LINT="YES"
    - POD_QUALITY_CHECK="NO"
  matrix:
    - SIMULATOR_NAME="iPhone 8" iOS_SDK="iphonesimulator13.2"
script:
  - Scripts/travis-ci.sh
