//
//  File.swift
//  Swift_UIKit_ChatApp
//
//  Created by Al-Tameemi Hayder on 26.10.2023.
//

let objectsEmojis: [EmojiObject] = [
    EmojiObject(keyWord: "File Folder", emoji: "📁"),
    EmojiObject(keyWord: "Open File Folder", emoji: "📂"),
    EmojiObject(keyWord: "Watch", emoji: "⌚"),
    EmojiObject(keyWord: "Mobile Phone", emoji: "📱"),
    EmojiObject(keyWord: "Mobile Phone with Arrow", emoji: "📲"),
    EmojiObject(keyWord: "Laptop", emoji: "💻"),
    EmojiObject(keyWord: "Desktop Computer", emoji: "⌨️"),
    EmojiObject(keyWord: "Computer Monitor", emoji: "🖥"),
    EmojiObject(keyWord: "Printer", emoji: "🖨"),
    EmojiObject(keyWord: "Computer Mouse", emoji: "🖱"),
    EmojiObject(keyWord: "Trackball", emoji: "🖲"),
    EmojiObject(keyWord: "Joystick", emoji: "🕹"),
    EmojiObject(keyWord: "Clamp", emoji: "🗜"),
    EmojiObject(keyWord: "Floppy Disk", emoji: "💽"),
    EmojiObject(keyWord: "Optical Disk", emoji: "💾"),
    EmojiObject(keyWord: "DVD", emoji: "💿"),
    EmojiObject(keyWord: "CD", emoji: "📀"),
    EmojiObject(keyWord: "Videocassette", emoji: "📼"),
    EmojiObject(keyWord: "Camera", emoji: "📷"),
    EmojiObject(keyWord: "Camera with Flash", emoji: "📸"),
    EmojiObject(keyWord: "Video Camera", emoji: "📹"),
    EmojiObject(keyWord: "Movie Camera", emoji: "🎥"),
    EmojiObject(keyWord: "Film Projector", emoji: "📽"),
    EmojiObject(keyWord: "Film Frames", emoji: "🎞"),
    EmojiObject(keyWord: "Telephone Receiver", emoji: "📞"),
    EmojiObject(keyWord: "Telephone", emoji: "☎️"),
    EmojiObject(keyWord: "Pager", emoji: "📟"),
    EmojiObject(keyWord: "Fax Machine", emoji: "📠"),
    EmojiObject(keyWord: "Television", emoji: "📺"),
    EmojiObject(keyWord: "Radio", emoji: "📻"),
    EmojiObject(keyWord: "Studio Microphone", emoji: "🎙"),
    EmojiObject(keyWord: "Level Slider", emoji: "🎚"),
    EmojiObject(keyWord: "Control Knobs", emoji: "🎛"),
    EmojiObject(keyWord: "Hourglass", emoji: "⏱"),
    EmojiObject(keyWord: "Hourglass with Flowing Sand", emoji: "⏲"),
    EmojiObject(keyWord: "Alarm Clock", emoji: "⏰"),
    EmojiObject(keyWord: "Mantelpiece Clock", emoji: "🕰"),
    EmojiObject(keyWord: "Hourglass Not Done", emoji: "⌛️"),
    EmojiObject(keyWord: "Hourglass Done", emoji: "⏳"),
    EmojiObject(keyWord: "Satellite Antenna", emoji: "📡"),
    EmojiObject(keyWord: "Battery", emoji: "🔋"),
    EmojiObject(keyWord: "Electric Plug", emoji: "🔌"),
    EmojiObject(keyWord: "Light Bulb", emoji: "💡"),
    EmojiObject(keyWord: "Flashlight", emoji: "🔦"),
    EmojiObject(keyWord: "Candle", emoji: "🕯"),
    EmojiObject(keyWord: "Wastebasket", emoji: "🗑"),
    EmojiObject(keyWord: "Oil Drum", emoji: "🛢"),
    EmojiObject(keyWord: "Money with Wings", emoji: "💸"),
    EmojiObject(keyWord: "Dollar Banknote", emoji: "💵"),
    EmojiObject(keyWord: "Yen Banknote", emoji: "💴"),
    EmojiObject(keyWord: "Euro Banknote", emoji: "💶"),
    EmojiObject(keyWord: "Pound Banknote", emoji: "💷"),
    EmojiObject(keyWord: "Money Bag", emoji: "💰"),
    EmojiObject(keyWord: "Credit Card", emoji: "💳"),
    EmojiObject(keyWord: "Gem Stone", emoji: "💎"),
    EmojiObject(keyWord: "Balance Scale", emoji: "⚖️"),
    EmojiObject(keyWord: "Wrench", emoji: "🔧"),
    EmojiObject(keyWord: "Hammer", emoji: "🔨"),
    EmojiObject(keyWord: "Pick", emoji: "⚒"),
    EmojiObject(keyWord: "Hammer and Pick", emoji: "🛠"),
    EmojiObject(keyWord: "Hammer and Wrench", emoji: "⛏"),
    EmojiObject(keyWord: "Screwdriver", emoji: "🔩"),
    EmojiObject(keyWord: "Gear", emoji: "⚙️"),
    EmojiObject(keyWord: "Chains", emoji: "⛓"),
    EmojiObject(keyWord: "Pistol", emoji: "🔫"),
    EmojiObject(keyWord: "Bomb", emoji: "💣"),
    EmojiObject(keyWord: "Knife", emoji: "🔪"),
    EmojiObject(keyWord: "Dagger", emoji: "🗡"),
    EmojiObject(keyWord: "Crossed Swords", emoji: "⚔️"),
    EmojiObject(keyWord: "Shield", emoji: "🛡"),
    EmojiObject(keyWord: "Cigarette", emoji: "🚬"),
    EmojiObject(keyWord: "Coffin", emoji: "⚰️"),
    EmojiObject(keyWord: "Funeral Urn", emoji: "⚱️"),
    EmojiObject(keyWord: "Amphora", emoji: "🏺"),
    EmojiObject(keyWord: "Crystal Ball", emoji: "🔮"),
    EmojiObject(keyWord: "Prayer Beads", emoji: "📿"),
    EmojiObject(keyWord: "Barber Pole", emoji: "💈"),
    EmojiObject(keyWord: "Alembic", emoji: "⚗️"),
    EmojiObject(keyWord: "Telescope", emoji: "🔭"),
    EmojiObject(keyWord: "Microscope", emoji: "🔬"),
    EmojiObject(keyWord: "Hole", emoji: "🕳"),
    EmojiObject(keyWord: "Pill", emoji: "💊"),
    EmojiObject(keyWord: "Syringe", emoji: "💉"),
    EmojiObject(keyWord: "Thermometer", emoji: "🌡"),
    EmojiObject(keyWord: "Toilet", emoji: "🚽"),
    EmojiObject(keyWord: "Potable Water", emoji: "🚰"),
    EmojiObject(keyWord: "Shower", emoji: "🚿"),
    EmojiObject(keyWord: "Bathtub", emoji: "🛁"),
    EmojiObject(keyWord: "Bed", emoji: "🛀"),
    EmojiObject(keyWord: "Bellhop Bell", emoji: "🛎"),
    EmojiObject(keyWord: "Key", emoji: "🔑"),
    EmojiObject(keyWord: "Old Key", emoji: "🗝"),
    EmojiObject(keyWord: "Door", emoji: "🚪"),
    EmojiObject(keyWord: "Couch and Lamp", emoji: "🛋"),
    EmojiObject(keyWord: "Bed", emoji: "🛏"),
    EmojiObject(keyWord: "Sleeping Bed", emoji: "🛌"),
    EmojiObject(keyWord: "Framed Picture", emoji: "🖼"),
    EmojiObject(keyWord: "Shopping Bags", emoji: "🛍"),
    EmojiObject(keyWord: "Shopping Cart", emoji: "🛒"),
    EmojiObject(keyWord: "Wrapped Gift", emoji: "🎁"),
    EmojiObject(keyWord: "Balloon", emoji: "🎈"),
    EmojiObject(keyWord: "Carp Streamer", emoji: "🎏"),
    EmojiObject(keyWord: "Ribbon", emoji: "🎀"),
    EmojiObject(keyWord: "Confetti Ball", emoji: "🎊"),
    EmojiObject(keyWord: "Party Popper", emoji: "🎉"),
    EmojiObject(keyWord: "Japanese Dolls", emoji: "🎎"),
    EmojiObject(keyWord: "Izakaya Lantern", emoji: "🏮"),
    EmojiObject(keyWord: "Wind Chime", emoji: "🎐"),
    EmojiObject(keyWord: "Envelope", emoji: "✉️"),
    EmojiObject(keyWord: "Incoming Envelope", emoji: "📩"),
    EmojiObject(keyWord: "Envelope with Arrow", emoji: "📨"),
    EmojiObject(keyWord: "Outbox Tray", emoji: "📧"),
    EmojiObject(keyWord: "Inbox Tray", emoji: "💌"),
    EmojiObject(keyWord: "Package", emoji: "📦"),
    EmojiObject(keyWord: "Label", emoji: "🏷"),
    EmojiObject(keyWord: "Mailbox Closed", emoji: "📪"),
    EmojiObject(keyWord: "Mailbox with No Mail", emoji: "📫"),
    EmojiObject(keyWord: "Mailbox with Mail", emoji: "📬"),
    EmojiObject(keyWord: "Mailbox with Raised Flag", emoji: "📭"),
    EmojiObject(keyWord: "Scroll", emoji: "📜"),
    EmojiObject(keyWord: "Page with Curl", emoji: "📃"),
    EmojiObject(keyWord: "Page Facing Up", emoji: "📄"),
    EmojiObject(keyWord: "Document", emoji: "📑"),
    EmojiObject(keyWord: "Card Index", emoji: "📇"),
    EmojiObject(keyWord: "Card File Box", emoji: "🗃"),
    EmojiObject(keyWord: "Ballot Box with Ballot", emoji: "🗳"),
    EmojiObject(keyWord: "File Cabinet", emoji: "🗄"),
    EmojiObject(keyWord: "Clipboard", emoji: "📋"),
    EmojiObject(keyWord: "File Folder", emoji: "📁"),
    EmojiObject(keyWord: "Open File Folder", emoji: "📂"),
    EmojiObject(keyWord: "Card Index Dividers", emoji: "🗂"),
    EmojiObject(keyWord: "Newspaper", emoji: "🗞"),
    EmojiObject(keyWord: "Rolled-Up Newspaper", emoji: "📰"),
    EmojiObject(keyWord: "Notebook", emoji: "📓"),
    EmojiObject(keyWord: "Notebook with Decorative Cover", emoji: "📔"),
    EmojiObject(keyWord: "Closed Book", emoji: "📕"),
    EmojiObject(keyWord: "Green Book", emoji: "📗"),
    EmojiObject(keyWord: "Blue Book", emoji: "📘"),
    EmojiObject(keyWord: "Orange Book", emoji: "📙"),
    EmojiObject(keyWord: "Books", emoji: "📚"),
    EmojiObject(keyWord: "Bookmark Tabs", emoji: "🔖"),
    EmojiObject(keyWord: "Link", emoji: "🔗"),
    EmojiObject(keyWord: "Paperclip", emoji: "📎"),
    EmojiObject(keyWord: "Linked Paperclips", emoji: "🖇"),
    EmojiObject(keyWord: "Triangular Ruler", emoji: "📐"),
    EmojiObject(keyWord: "Straight Ruler", emoji: "📏"),
    EmojiObject(keyWord: "Pushpin", emoji: "📌"),
    EmojiObject(keyWord: "Round Pushpin", emoji: "📍"),
    EmojiObject(keyWord: "Scissors", emoji: "✂️"),
    EmojiObject(keyWord: "Ballpoint Pen", emoji: "🖊"),
    EmojiObject(keyWord: "Fountain Pen", emoji: "🖋"),
    EmojiObject(keyWord: "Black Nib", emoji: "✒️"),
    EmojiObject(keyWord: "Paintbrush", emoji: "🖌"),
    EmojiObject(keyWord: "Crayon", emoji: "🖍"),
    EmojiObject(keyWord: "Memo", emoji: "📝"),
    EmojiObject(keyWord: "Magnifying Glass Tilted Left", emoji: "🔍"),
    EmojiObject(keyWord: "Magnifying Glass Tilted Right", emoji: "🔎"),
    EmojiObject(keyWord: "Lock with Ink Pen", emoji: "🔏"),
    EmojiObject(keyWord: "Closed Lock with Key", emoji: "🔐"),
    EmojiObject(keyWord: "Lock", emoji: "🔒"),
    EmojiObject(keyWord: "Open Lock", emoji: "🔓")
]
