//
//  symbols.swift
//  Swift_UIKit_ChatApp
//
//  Created by Al-Tameemi Hayder on 26.10.2023.
//

let symbolsEmojis: [EmojiObject] = [
    EmojiObject(keyWord: "Red Heart", emoji: "❤️"),
    EmojiObject(keyWord: "Yellow Heart", emoji: "💛"),
    EmojiObject(keyWord: "Green Heart", emoji: "💚"),
    EmojiObject(keyWord: "Blue Heart", emoji: "💙"),
    EmojiObject(keyWord: "Purple Heart", emoji: "💜"),
    EmojiObject(keyWord: "Black Heart", emoji: "🖤"),
    EmojiObject(keyWord: "Broken Heart", emoji: "💔"),
    EmojiObject(keyWord: "Heavy Heart Exclamation", emoji: "❣️"),
    EmojiObject(keyWord: "Two Hearts", emoji: "💕"),
    EmojiObject(keyWord: "Revolving Hearts", emoji: "💞"),
    EmojiObject(keyWord: "Beating Heart", emoji: "💓"),
    EmojiObject(keyWord: "Growing Heart", emoji: "💗"),
    EmojiObject(keyWord: "Sparkling Heart", emoji: "💖"),
    EmojiObject(keyWord: "Heart with Arrow", emoji: "💘"),
    EmojiObject(keyWord: "Heart with Ribbon", emoji: "💝"),
    EmojiObject(keyWord: "Heart Decoration", emoji: "💟"),
    EmojiObject(keyWord: "Peace Symbol", emoji: "☮️"),
    EmojiObject(keyWord: "Latin Cross", emoji: "✝️"),
    EmojiObject(keyWord: "Star and Crescent", emoji: "☪️"),
    EmojiObject(keyWord: "Om", emoji: "🕉"),
    EmojiObject(keyWord: "Wheel of Dharma", emoji: "☸️"),
    EmojiObject(keyWord: "Star of David", emoji: "✡️"),
    EmojiObject(keyWord: "Six Pointed Star with Middle Dot", emoji: "🔯"),
    EmojiObject(keyWord: "Menorah with Nine Branches", emoji: "🕎"),
    EmojiObject(keyWord: "Yin Yang", emoji: "☯️"),
    EmojiObject(keyWord: "Orthodox Cross", emoji: "☦️"),
    EmojiObject(keyWord: "Place of Worship", emoji: "🛐"),
    EmojiObject(keyWord: "Ophiuchus", emoji: "⛎"),
    EmojiObject(keyWord: "Aries", emoji: "♈️"),
    EmojiObject(keyWord: "Taurus", emoji: "♉️"),
    EmojiObject(keyWord: "Gemini", emoji: "♊️"),
    EmojiObject(keyWord: "Cancer", emoji: "♋️"),
    EmojiObject(keyWord: "Leo", emoji: "♌️"),
    EmojiObject(keyWord: "Virgo", emoji: "♍️"),
    EmojiObject(keyWord: "Libra", emoji: "♎️"),
    EmojiObject(keyWord: "Scorpio", emoji: "♏️"),
    EmojiObject(keyWord: "Sagittarius", emoji: "♐️"),
    EmojiObject(keyWord: "Capricorn", emoji: "♑️"),
    EmojiObject(keyWord: "Aquarius", emoji: "♒️"),
    EmojiObject(keyWord: "Pisces", emoji: "♓️"),
    EmojiObject(keyWord: "ID Button", emoji: "🆔"),
    EmojiObject(keyWord: "Atom Symbol", emoji: "⚛️"),
    EmojiObject(keyWord: "Japanese Button", emoji: "🉑"),
    EmojiObject(keyWord: "Radioactive", emoji: "☢️"),
    EmojiObject(keyWord: "Biohazard", emoji: "☣️"),
    EmojiObject(keyWord: "Mobile Phone Off", emoji: "📴"),
    EmojiObject(keyWord: "Vibration Mode", emoji: "📳"),
    EmojiObject(keyWord: "Japanese Button", emoji: "🈶"),
    EmojiObject(keyWord: "Japanese Button", emoji: "🈚️"),
    EmojiObject(keyWord: "Japanese Button", emoji: "🈸"),
    EmojiObject(keyWord: "Japanese Button", emoji: "🈺"),
    EmojiObject(keyWord: "Japanese Button", emoji: "🈷️"),
    EmojiObject(keyWord: "Eight-Pointed Star", emoji: "✴️"),
    EmojiObject(keyWord: "Japanese Button", emoji: "🆚"),
    EmojiObject(keyWord: "White Flower", emoji: "💮"),
    EmojiObject(keyWord: "Japanese Button", emoji: "🉐"),
    EmojiObject(keyWord: "Japanese Button", emoji: "㊙️"),
    EmojiObject(keyWord: "Japanese Button", emoji: "㊗️"),
    EmojiObject(keyWord: "Japanese Button", emoji: "🈴"),
    EmojiObject(keyWord: "Japanese Button", emoji: "🈵"),
    EmojiObject(keyWord: "Japanese Button", emoji: "🈹"),
    EmojiObject(keyWord: "Japanese Button", emoji: "🈲"),
    EmojiObject(keyWord: "Negative Squared Latin Capital Letter A", emoji: "🅰️"),
    EmojiObject(keyWord: "Negative Squared Latin Capital Letter B", emoji: "🅱️"),
    EmojiObject(keyWord: "Negative Squared Ab", emoji: "🆎"),
    EmojiObject(keyWord: "Negative Squared Cl", emoji: "🆑"),
    EmojiObject(keyWord: "Negative Squared Latin Capital Letter O", emoji: "🅾️"),
    EmojiObject(keyWord: "SOS Button", emoji: "🆘"),
    EmojiObject(keyWord: "Cross Mark", emoji: "❌"),
    EmojiObject(keyWord: "Heavy Large Circle", emoji: "⭕️"),
    EmojiObject(keyWord: "Octagonal Sign", emoji: "🛑"),
    EmojiObject(keyWord: "No Entry", emoji: "⛔️"),
    EmojiObject(keyWord: "Name Badge", emoji: "📛"),
    EmojiObject(keyWord: "Prohibited", emoji: "🚫"),
    EmojiObject(keyWord: "Hundred Points", emoji: "💯"),
    EmojiObject(keyWord: "Anger Symbol", emoji: "💢"),
    EmojiObject(keyWord: "Hot Springs", emoji: "♨️"),
    EmojiObject(keyWord: "No Pedestrians", emoji: "🚷"),
    EmojiObject(keyWord: "No Bicycles", emoji: "🚯"),
    EmojiObject(keyWord: "No Smoking", emoji: "🚭"),
    EmojiObject(keyWord: "No One Under Eighteen", emoji: "🔞"),
    EmojiObject(keyWord: "No Mobile Phones", emoji: "📵"),
    EmojiObject(keyWord: "Do Not Litter", emoji: "🚮"),
    EmojiObject(keyWord: "Double Exclamation Mark", emoji: "‼️"),
    EmojiObject(keyWord: "Exclamation Question Mark", emoji: "⁉️"),
    EmojiObject(keyWord: "Dim Button", emoji: "🔅"),
    EmojiObject(keyWord: "Bright Button", emoji: "🔆"),
    EmojiObject(keyWord: "Part Alternation Mark", emoji: "〽️"),
    EmojiObject(keyWord: "Warning", emoji: "⚠️"),
    EmojiObject(keyWord: "Children Crossing", emoji: "🚸"),
    EmojiObject(keyWord: "Trident Emblem", emoji: "🔱"),
    EmojiObject(keyWord: "Fleur-de-Lis", emoji: "⚜️"),
    EmojiObject(keyWord: "Japanese Button", emoji: "🔰"),
    EmojiObject(keyWord: "Recycling Symbol", emoji: "♻️"),
    EmojiObject(keyWord: "Check Mark Button", emoji: "✅"),
    EmojiObject(keyWord: "Japanese Button", emoji: "🈯️"),
    EmojiObject(keyWord: "Chart Increasing with Yen", emoji: "💹"),
    EmojiObject(keyWord: "Sparkle", emoji: "❇️"),
    EmojiObject(keyWord: "Eight-Spoked Asterisk", emoji: "✳️"),
    EmojiObject(keyWord: "Negative Squared Cross Mark", emoji: "❎"),
    EmojiObject(keyWord: "Globe with Meridians", emoji: "🌐"),
    EmojiObject(keyWord: "Diamond Shape with a Dot Inside", emoji: "💠"),
    EmojiObject(keyWord: "Circled M", emoji: "Ⓜ️"),
    EmojiObject(keyWord: "Cyclone", emoji: "🌀"),
    EmojiObject(keyWord: "Sleeping Accommodation", emoji: "💤"),
    EmojiObject(keyWord: "Automated Teller Machine", emoji: "🏧"),
    EmojiObject(keyWord: "Water Closet", emoji: "🚾"),
    EmojiObject(keyWord: "Wheelchair Symbol", emoji: "♿️"),
    EmojiObject(keyWord: "Parking", emoji: "🅿️"),
    EmojiObject(keyWord: "Squared Katakana Koko", emoji: "🈳"),
    EmojiObject(keyWord: "Squared Katakana Sa", emoji: "🈂️"),
    EmojiObject(keyWord: "Passport Control", emoji: "🛂"),
    EmojiObject(keyWord: "Customs", emoji: "🛃"),
    EmojiObject(keyWord: "Baggage Claim", emoji: "🛄"),
    EmojiObject(keyWord: "Left Luggage", emoji: "🛅"),
    EmojiObject(keyWord: "Mens Symbol", emoji: "🚹"),
    EmojiObject(keyWord: "Womens Symbol", emoji: "🚺"),
    EmojiObject(keyWord: "Baby Symbol", emoji: "🚼"),
    EmojiObject(keyWord: "Restroom", emoji: "🚻"),
    EmojiObject(keyWord: "Put Litter in Its Place", emoji: "🚮"),
    EmojiObject(keyWord: "Cinema", emoji: "🎦"),
    EmojiObject(keyWord: "Antenna Bars", emoji: "📶"),
    EmojiObject(keyWord: "Squared Katakana Katakana", emoji: "🈁"),
    EmojiObject(keyWord: "Input Symbol for Latin Capital Letters", emoji: "🔣"),
    EmojiObject(keyWord: "Information Source", emoji: "ℹ️"),
    EmojiObject(keyWord: "Input Symbol for Latin Small Letters", emoji: "🔤"),
    EmojiObject(keyWord: "Input Symbol for Latin Letters", emoji: "🔡"),
    EmojiObject(keyWord: "Input Symbol for Numbers", emoji: "🔠"),
    EmojiObject(keyWord: "Squared NG", emoji: "🆖"),
    EmojiObject(keyWord: "Squared OK", emoji: "🆗"),
    EmojiObject(keyWord: "Squared Up with Exclamation Mark", emoji: "🆙"),
    EmojiObject(keyWord: "Squared New", emoji: "🆒"),
    EmojiObject(keyWord: "Squared Free", emoji: "🆓"),
    EmojiObject(keyWord: "Keycap 0", emoji: "0️⃣"),
    EmojiObject(keyWord: "Keycap 1", emoji: "1️⃣"),
    EmojiObject(keyWord: "Keycap 2", emoji: "2️⃣"),
    EmojiObject(keyWord: "Keycap 3", emoji: "3️⃣"),
    EmojiObject(keyWord: "Keycap 4", emoji: "4️⃣"),
    EmojiObject(keyWord: "Keycap 5", emoji: "5️⃣"),
    EmojiObject(keyWord: "Keycap 6", emoji: "6️⃣"),
    EmojiObject(keyWord: "Keycap 7", emoji: "7️⃣"),
    EmojiObject(keyWord: "Keycap 8", emoji: "8️⃣"),
    EmojiObject(keyWord: "Keycap 9", emoji: "9️⃣"),
    EmojiObject(keyWord: "Keycap 10", emoji: "🔟"),
    EmojiObject(keyWord: "Keycap #", emoji: "#️⃣"),
    EmojiObject(keyWord: "Keycap *", emoji: "*️⃣"),
    EmojiObject(keyWord: "Play Button", emoji: "▶️"),
    EmojiObject(keyWord: "Double Vertical Bar", emoji: "⏸"),
    EmojiObject(keyWord: "Black Right-Pointing Triangle with Double Vertical Bar", emoji: "⏯"),
    EmojiObject(keyWord: "Black Right-Pointing Small Triangle", emoji: "⏹"),
    EmojiObject(keyWord: "Black Left-Pointing Double Triangle", emoji: "⏺"),
    EmojiObject(keyWord: "Black Right-Pointing Double Triangle", emoji: "⏭"),
    EmojiObject(keyWord: "Black Left-Pointing Double Triangle with Vertical Bar", emoji: "⏮"),
    EmojiObject(keyWord: "Black Right-Pointing Triangle with Double Vertical Bar", emoji: "⏩"),
    EmojiObject(keyWord: "Black Left-Pointing Triangle with Double Vertical Bar", emoji: "⏪"),
    EmojiObject(keyWord: "Up-Pointing Small Red Triangle", emoji: "⏫"),
    EmojiObject(keyWord: "Down-Pointing Small Red Triangle", emoji: "⏬"),
    EmojiObject(keyWord: "Black Left-Pointing Triangle", emoji: "◀️"),
    EmojiObject(keyWord: "Up-Pointing Small Red Triangle", emoji: "🔼"),
    EmojiObject(keyWord: "Down-Pointing Small Red Triangle", emoji: "🔽"),
    EmojiObject(keyWord: "Right-Pointing Triangle", emoji: "➡️"),
    EmojiObject(keyWord: "Left-Pointing Triangle", emoji: "⬅️"),
    EmojiObject(keyWord: "Up-Pointing Triangle", emoji: "⬆️"),
    EmojiObject(keyWord: "Down-Pointing Triangle", emoji: "⬇️"),
    EmojiObject(keyWord: "North East Arrow", emoji: "↗️"),
    EmojiObject(keyWord: "North West Arrow", emoji: "↖️"),
    EmojiObject(keyWord: "South East Arrow", emoji: "↘️"),
    EmojiObject(keyWord: "South West Arrow", emoji: "↙️"),
    EmojiObject(keyWord: "Up Down Arrow", emoji: "↕️"),
    EmojiObject(keyWord: "Left Right Arrow", emoji: "↔️"),
    EmojiObject(keyWord: "Left Arrow Curving Right", emoji: "↪️"),
    EmojiObject(keyWord: "Left Arrow Curving Left", emoji: "↩️"),
    EmojiObject(keyWord: "Upwards Button", emoji: "⤴️"),
    EmojiObject(keyWord: "Downwards Button", emoji: "⤵️"),
    EmojiObject(keyWord: "Shuffle Tracks Button", emoji: "🔀"),
    EmojiObject(keyWord: "Repeat Button", emoji: "🔁"),
    EmojiObject(keyWord: "Repeat Single Button", emoji: "🔂"),
    EmojiObject(keyWord: "Cyclone Button", emoji: "🔄"),
    EmojiObject(keyWord: "Musical Note", emoji: "🎵"),
    EmojiObject(keyWord: "Musical Notes", emoji: "🎶"),
    EmojiObject(keyWord: "Heavy Plus Sign", emoji: "➕"),
    EmojiObject(keyWord: "Heavy Minus Sign", emoji: "➖"),
    EmojiObject(keyWord: "Heavy Division Sign", emoji: "➗"),
    EmojiObject(keyWord: "Heavy Dollar Sign", emoji: "💲"),
    EmojiObject(keyWord: "Heavy Currency Sign", emoji: "💱"),
    EmojiObject(keyWord: "Trade Mark Sign", emoji: "™️"),
    EmojiObject(keyWord: "Copyright Sign", emoji: "©️"),
    EmojiObject(keyWord: "Registered Sign", emoji: "®️"),
    EmojiObject(keyWord: "Wavy Dash", emoji: "〰️"),
    EmojiObject(keyWord: "Curly Loop", emoji: "➰"),
    EmojiObject(keyWord: "Double Curly Loop", emoji: "➿"),
    EmojiObject(keyWord: "END Arrow", emoji: "🔚"),
    EmojiObject(keyWord: "Back Arrow", emoji: "🔙"),
    EmojiObject(keyWord: "On! Arrow", emoji: "🔛"),
    EmojiObject(keyWord: "TOP Arrow", emoji: "🔝"),
    EmojiObject(keyWord: "SOON Arrow", emoji: "🔜"),
    EmojiObject(keyWord: "Check Box with Check", emoji: "✔️"),
    EmojiObject(keyWord: "Ballot Box with Check", emoji: "☑️"),
    EmojiObject(keyWord: "Radio Button", emoji: "🔘"),
    EmojiObject(keyWord: "White Circle", emoji: "⚪️"),
    EmojiObject(keyWord: "Black Circle", emoji: "⚫️"),
    EmojiObject(keyWord: "Large Red Circle", emoji: "🔴"),
    EmojiObject(keyWord: "Large Blue Circle", emoji: "🔵"),
    EmojiObject(keyWord: "Red Triangle Pointed Up", emoji: "🔺"),
    EmojiObject(keyWord: "Red Triangle Pointed Down", emoji: "🔻"),
    EmojiObject(keyWord: "Small Orange Diamond", emoji: "🔸"),
    EmojiObject(keyWord: "Small Blue Diamond", emoji: "🔹"),
    EmojiObject(keyWord: "Large Orange Diamond", emoji: "🔶"),
    EmojiObject(keyWord: "Large Blue Diamond", emoji: "🔷"),
    EmojiObject(keyWord: "Small Orange Diamond", emoji: "🔳"),
    EmojiObject(keyWord: "Small Blue Diamond", emoji: "🔲"),
    EmojiObject(keyWord: "Black Small Square", emoji: "▪️"),
    EmojiObject(keyWord: "White Small Square", emoji: "▫️"),
    EmojiObject(keyWord: "Black Medium Small Square", emoji: "◾️"),
    EmojiObject(keyWord: "White Medium Small Square", emoji: "◽️"),
    EmojiObject(keyWord: "Black Medium Square", emoji: "◼️"),
    EmojiObject(keyWord: "White Medium Square", emoji: "◻️"),
    EmojiObject(keyWord: "Black Large Square", emoji: "⬛️"),
    EmojiObject(keyWord: "White Large Square", emoji: "⬜️"),
    EmojiObject(keyWord: "Speaker", emoji: "🔈"),
    EmojiObject(keyWord: "Speaker with Cancellation Stroke", emoji: "🔇"),
    EmojiObject(keyWord: "Speaker with One Sound Wave", emoji: "🔉"),
    EmojiObject(keyWord: "Speaker with Three Sound Waves", emoji: "🔊"),
    EmojiObject(keyWord: "Bell", emoji: "🔔"),
    EmojiObject(keyWord: "Bell with Cancellation Stroke", emoji: "🔕"),
    EmojiObject(keyWord: "Megaphone", emoji: "📣"),
    EmojiObject(keyWord: "Postal Horn", emoji: "📢"),
    EmojiObject(keyWord: "Eye in Speech Bubble", emoji: "👁‍🗨"),
    EmojiObject(keyWord: "Left Speech Bubble", emoji: "💬"),
    EmojiObject(keyWord: "Right Anger Bubble", emoji: "💭"),
    EmojiObject(keyWord: "Thought Balloon", emoji: "🗯"),
    EmojiObject(keyWord: "Spade Suit", emoji: "♠️"),
    EmojiObject(keyWord: "Club Suit", emoji: "♣️"),
    EmojiObject(keyWord: "Heart Suit", emoji: "♥️"),
    EmojiObject(keyWord: "Diamond Suit", emoji: "♦️"),
    EmojiObject(keyWord: "Playing Card Black Joker", emoji: "🃏"),
    EmojiObject(keyWord: "Flower Playing Cards", emoji: "🎴"),
    EmojiObject(keyWord: "Clock Face One OClock", emoji: "🕐"),
    EmojiObject(keyWord: "Clock Face Two OClock", emoji: "🕑"),
    EmojiObject(keyWord: "Clock Face Three OClock", emoji: "🕒"),
    EmojiObject(keyWord: "Clock Face Four OClock", emoji: "🕓"),
    EmojiObject(keyWord: "Clock Face Five OClock", emoji: "🕔"),
    EmojiObject(keyWord: "Clock Face Six OClock", emoji: "🕕"),
    EmojiObject(keyWord: "Clock Face Seven OClock", emoji: "🕖"),
    EmojiObject(keyWord: "Clock Face Eight OClock", emoji: "🕗"),
    EmojiObject(keyWord: "Clock Face Nine OClock", emoji: "🕘"),
    EmojiObject(keyWord: "Clock Face Ten OClock", emoji: "🕙"),
    EmojiObject(keyWord: "Clock Face Eleven OClock", emoji: "🕚"),
    EmojiObject(keyWord: "Clock Face Twelve OClock", emoji: "🕛"),
    EmojiObject(keyWord: "Clock Face One-Thirty", emoji: "🕜"),
    EmojiObject(keyWord: "Clock Face Two-Thirty", emoji: "🕝"),
    EmojiObject(keyWord: "Clock Face Three-Thirty", emoji: "🕞"),
    EmojiObject(keyWord: "Clock Face Four-Thirty", emoji: "🕟"),
    EmojiObject(keyWord: "Clock Face Five-Thirty", emoji: "🕠"),
    EmojiObject(keyWord: "Clock Face Six-Thirty", emoji: "🕡"),
    EmojiObject(keyWord: "Clock Face Seven-Thirty", emoji: "🕢"),
    EmojiObject(keyWord: "Clock Face Eight-Thirty", emoji: "🕣"),
    EmojiObject(keyWord: "Clock Face Nine-Thirty", emoji: "🕤"),
    EmojiObject(keyWord: "Clock Face Ten-Thirty", emoji: "🕥"),
    EmojiObject(keyWord: "Clock Face Eleven-Thirty", emoji: "🕦"),
    EmojiObject(keyWord: "Clock Face Twelve-Thirty", emoji: "🕧")
]

