//
//  travelAndPlacesEmojisArray.swift
//  Swift_UIKit_ChatApp
//
//  Created by Al-Tameemi Hayder on 26.10.2023.
//

let travelAndPlacesEmojis: [EmojiObject] = [
    EmojiObject(keyWord: "Automobile", emoji: "🚗"),
    EmojiObject(keyWord: "Taxi", emoji: "🚕"),
    EmojiObject(keyWord: "Sport Utility Vehicle", emoji: "🚙"),
    EmojiObject(keyWord: "Bus", emoji: "🚌"),
    EmojiObject(keyWord: "Trolleybus", emoji: "🚎"),
    EmojiObject(keyWord: "Racing Car", emoji: "🏎"),
    EmojiObject(keyWord: "Police Car", emoji: "🚓"),
    EmojiObject(keyWord: "Ambulance", emoji: "🚑"),
    EmojiObject(keyWord: "Fire Engine", emoji: "🚒"),
    EmojiObject(keyWord: "Minibus", emoji: "🚐"),
    EmojiObject(keyWord: "Delivery Truck", emoji: "🚚"),
    EmojiObject(keyWord: "Articulated Lorry", emoji: "🚛"),
    EmojiObject(keyWord: "Kick Scooter", emoji: "🛴"),
    EmojiObject(keyWord: "Bicycle", emoji: "🚲"),
    EmojiObject(keyWord: "Motor Scooter", emoji: "🛵"),
    EmojiObject(keyWord: "Motorcycle", emoji: "🏍"),
    EmojiObject(keyWord: "Police Car Light", emoji: "🚨"),
    EmojiObject(keyWord: "Police Car", emoji: "🚔"),
    EmojiObject(keyWord: "Oncoming Bus", emoji: "🚍"),
    EmojiObject(keyWord: "Oncoming Automobile", emoji: "🚘"),
    EmojiObject(keyWord: "Oncoming Taxi", emoji: "🚖"),
    EmojiObject(keyWord: "Aerial Tramway", emoji: "🚡"),
    EmojiObject(keyWord: "Mountain Cableway", emoji: "🚠"),
    EmojiObject(keyWord: "Suspension Railway", emoji: "🚟"),
    EmojiObject(keyWord: "Railway Car", emoji: "🚃"),
    EmojiObject(keyWord: "Tram Car", emoji: "🚋"),
    EmojiObject(keyWord: "Monorail", emoji: "🚞"),
    EmojiObject(keyWord: "Light Rail", emoji: "🚝"),
    EmojiObject(keyWord: "High-Speed Train", emoji: "🚄"),
    EmojiObject(keyWord: "High-Speed Train with Bullet Nose", emoji: "🚅"),
    EmojiObject(keyWord: "Train", emoji: "🚈"),
    EmojiObject(keyWord: "Locomotive", emoji: "🚂"),
    EmojiObject(keyWord: "Railway Car", emoji: "🚆"),
    EmojiObject(keyWord: "Subway", emoji: "🚇"),
    EmojiObject(keyWord: "Station", emoji: "🚊"),
    EmojiObject(keyWord: "Tram", emoji: "🚉"),
    EmojiObject(keyWord: "Helicopter", emoji: "🚁"),
    EmojiObject(keyWord: "Small Airplane", emoji: "🛩"),
    EmojiObject(keyWord: "Airplane", emoji: "✈️"),
    EmojiObject(keyWord: "Airplane Departure", emoji: "🛫"),
    EmojiObject(keyWord: "Airplane Arrival", emoji: "🛬"),
    EmojiObject(keyWord: "Rocket", emoji: "🚀"),
    EmojiObject(keyWord: "Satellite", emoji: "🛰"),
    EmojiObject(keyWord: "Seat", emoji: "💺"),
    EmojiObject(keyWord: "Canoe", emoji: "🛶"),
    EmojiObject(keyWord: "Sailboat", emoji: "⛵️"),
    EmojiObject(keyWord: "Motor Boat", emoji: "🛥"),
    EmojiObject(keyWord: "Speedboat", emoji: "🚤"),
    EmojiObject(keyWord: "Passenger Ship", emoji: "🛳"),
    EmojiObject(keyWord: "Ferry", emoji: "⛴"),
    EmojiObject(keyWord: "Ship", emoji: "🚢"),
    EmojiObject(keyWord: "Anchor", emoji: "⚓️"),
    EmojiObject(keyWord: "Construction Sign", emoji: "🚧"),
    EmojiObject(keyWord: "Fuel Pump", emoji: "⛽️"),
    EmojiObject(keyWord: "Bus Stop", emoji: "🚏"),
    EmojiObject(keyWord: "Vertical Traffic Light", emoji: "🚦"),
    EmojiObject(keyWord: "Horizontal Traffic Light", emoji: "🚥"),
    EmojiObject(keyWord: "World Map", emoji: "🗺"),
    EmojiObject(keyWord: "Moyai", emoji: "🗿"),
    EmojiObject(keyWord: "Statue of Liberty", emoji: "🗽"),
    EmojiObject(keyWord: "Fountain", emoji: "⛲️"),
    EmojiObject(keyWord: "Tokyo Tower", emoji: "🗼"),
    EmojiObject(keyWord: "Japanese Castle", emoji: "🏰"),
    EmojiObject(keyWord: "European Castle", emoji: "🏯"),
    EmojiObject(keyWord: "Stadium", emoji: "🏟"),
    EmojiObject(keyWord: "Ferris Wheel", emoji: "🎡"),
    EmojiObject(keyWord: "Roller Coaster", emoji: "🎢"),
    EmojiObject(keyWord: "Carousel Horse", emoji: "🎠"),
    EmojiObject(keyWord: "Umbrella on Ground", emoji: "⛱"),
    EmojiObject(keyWord: "Beach with Umbrella", emoji: "🏖"),
    EmojiObject(keyWord: "Desert Island", emoji: "🏝"),
    EmojiObject(keyWord: "Mountain", emoji: "⛰"),
    EmojiObject(keyWord: "Mountain with Sun", emoji: "🏔"),
    EmojiObject(keyWord: "Mount Fuji", emoji: "🗻"),
    EmojiObject(keyWord: "Volcano", emoji: "🌋"),
    EmojiObject(keyWord: "Desert", emoji: "🏜"),
    EmojiObject(keyWord: "Camping", emoji: "🏕"),
    EmojiObject(keyWord: "Tent", emoji: "⛺️"),
    EmojiObject(keyWord: "Railway Track", emoji: "🛤"),
    EmojiObject(keyWord: "Motorway", emoji: "🛣"),
    EmojiObject(keyWord: "Building Construction", emoji: "🏗"),
    EmojiObject(keyWord: "Factory", emoji: "🏭"),
    EmojiObject(keyWord: "House", emoji: "🏠"),
    EmojiObject(keyWord: "House with Garden", emoji: "🏡"),
    EmojiObject(keyWord: "Office Building", emoji: "🏢"),
    EmojiObject(keyWord: "Japanese Post Office", emoji: "🏬"),
    EmojiObject(keyWord: "European Post Office", emoji: "🏣"),
    EmojiObject(keyWord: "Hospital", emoji: "🏥"),
    EmojiObject(keyWord: "Bank", emoji: "🏦"),
    EmojiObject(keyWord: "Hotel", emoji: "🏨"),
    EmojiObject(keyWord: "Convenience Store", emoji: "🏪"),
    EmojiObject(keyWord: "School", emoji: "🏫"),
    EmojiObject(keyWord: "Love Hotel", emoji: "🏩"),
    EmojiObject(keyWord: "Wedding", emoji: "💒"),
    EmojiObject(keyWord: "Classical Building", emoji: "🏛"),
    EmojiObject(keyWord: "Church", emoji: "⛪️"),
    EmojiObject(keyWord: "Mosque", emoji: "🕌"),
    EmojiObject(keyWord: "Synagogue", emoji: "🕍"),
    EmojiObject(keyWord: "Shinto Shrine", emoji: "🕋"),
    EmojiObject(keyWord: "Pagoda", emoji: "⛩"),
    EmojiObject(keyWord: "Japan", emoji: "🗾"),
    EmojiObject(keyWord: "Sunrise Over Mountains", emoji: "🎑"),
    EmojiObject(keyWord: "National Park", emoji: "🏞"),
    EmojiObject(keyWord: "Sunrise", emoji: "🌅"),
    EmojiObject(keyWord: "Sunset", emoji: "🌄"),
    EmojiObject(keyWord: "Milky Way", emoji: "🌠"),
    EmojiObject(keyWord: "Shooting Star", emoji: "🎇"),
    EmojiObject(keyWord: "Fireworks", emoji: "🎆"),
    EmojiObject(keyWord: "Cityscape at Dusk", emoji: "🌇"),
    EmojiObject(keyWord: "Cityscape", emoji: "🏙"),
    EmojiObject(keyWord: "Night with Stars", emoji: "🌃"),
    EmojiObject(keyWord: "Bridge at Night", emoji: "🌉"),
    EmojiObject(keyWord: "Milky Way", emoji: "🌌"),
    EmojiObject(keyWord: "Foggy", emoji: "🌁"),
    EmojiObject(keyWord: "Cricket", emoji: "🦗"),
    EmojiObject(keyWord: "Flying Saucer", emoji: "🛸"),
    EmojiObject(keyWord: "Sled", emoji: "🛷"),
    EmojiObject(keyWord: "Curling Stone", emoji: "🥌")
]

